<!DOCTYPE html>
<html xmlns:wb="http://open.weibo.com/wb">
<head>
    <meta charset="utf-8" />
    <meta name="renderer" content="webkit">
    <meta name="keywords" content=""/>
    <meta name="description" content="" />
    <title>国际/港澳台机票首页</title>
    <link type="text/css" rel="stylesheet" href="//misc.360buyimg.com/??jdf/1.0.0/unit/ui-base/5.0.0/ui-base.css,jdf/1.0.0/unit/shortcut/5.0.0/shortcut.css,jdf/1.0.0/unit/global-header/5.0.0/global-header.css,jdf/1.0.0/unit/myjd/5.0.0/myjd.css,jdf/1.0.0/unit/nav/5.0.0/nav.css,jdf/1.0.0/unit/shoppingcart/5.0.0/shoppingcart.css,jdf/1.0.0/unit/global-footer/5.0.0/global-footer.css,jdf/1.0.0/unit/service/5.0.0/service.css,channel/lib/1.3.0/css/channel-base.css">
	<link type="text/css" rel="stylesheet" href="//misc.360buyimg.com/virtuals/??ui/css/ui.css,lvyou/2015/css/nav.css"/>
	<link rel="stylesheet" type="text/css" href="//misc.360buyimg.com/virtuals/ijipiao/2.0/css/index.css"/>
	<link rel="stylesheet" href="//misc.360buyimg.com/virtuals/ijipiao/2.0/css/index-jipiaof.css">
	<script type="text/javascript" src="//misc.360buyimg.com/??jdf/1.0.0/unit/base/5.0.0/base.js,jdf/lib/jquery-1.6.4.js"> </script>
	<script src="//misc.360buyimg.com/virtuals/ijipiao/2.0/js/data/cityGn.js"></script>
	<!-- Jimmy Shan 2017-06-12 add icon -->
	<link rel="icon" href="//www.jd.com/favicon.ico" mce_href="//www.jd.com/favicon.ico" type="image/x-icon">
    <script>
    	window.pageConfig = {
            compatible: true,
            gridWideClass: '',
            gridNarClass: '',
            jdVersion: '2.0.0',
            feedBackUrl: 'http://surveys.jd.com/index.php?r=survey/index/sid/82224/lang/zh-Hans'
        }
    </script>
    <script src="//misc.360buyimg.com/virtuals/ijipiao/2.0/js/art.js"></script>
</head>
<body class="root61" sidebar>
<script type="text/javascript">
    seajs.use(['jdf/1.0.0/unit/shortcut/5.0.0/shortcut'],function(shortcut){
        shortcut();
    });  
</script>

<!-- Global header -->
<!--  /widget/header/header.vm start-->
    <!--  /ijipiao_Shortcut_gbk.html -->

<!--/ijipiao_Shortcut_gbk.html -->

<!--shortcut start-->
<div id="shortcut-2014">
	<div class="w">
    	<ul class="fl">
    		<li id="ttbar-home"><i class="iconfont">&#xe608;</i><a href="//www.jd.com/" target="_blank">京东首页</a></li>
    	</ul>
    	<ul class="fr">
			<li class="fore1" id="ttbar-login">
				<a href="javascript:login();" class="link-login">你好，请登录</a>&nbsp;&nbsp;<a href="javascript:regist();" class="link-regist style-red">免费注册</a>
			</li>
			<li class="spacer"></li>
			<li class="fore2">
				<div class="dt">
					<a target="_blank" href="//order.jd.com/center/list.action">我的订单</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore3 dorpdown" id="ttbar-myjd">
				<div class="dt cw-icon">
					<!-- <i class="ci-right"><s>◇</s></i> -->
					<a target="_blank" href="//home.jd.com/">我的京东</a><i class="iconfont">&#xe605;</i>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore4">
				<div class="dt">
					<a target="_blank" href="//vip.jd.com/">京东会员</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore5">
				<div class="dt">
					<a target="_blank" href="//b.jd.com/">企业采购</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore6 dorpdown" id="ttbar-serv">
				<div class="dt cw-icon">
					<!-- <i class="ci-right"><s>◇</s></i> -->
					客户服务<i class="iconfont">&#xe605;</i>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore7 dorpdown" id="ttbar-navs">
				<div class="dt cw-icon">
					<!-- <i class="ci-right"><s>◇</s></i> -->
					网站导航<i class="iconfont">&#xe605;</i>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore8 dorpdown" id="ttbar-apps">
				<div class="dt cw-icon">
					<!-- <i class="ci-left"></i> -->
					<!-- <i class="ci-right"><s>◇</s></i> -->
					<a target="_blank" href="//app.jd.com/">手机京东</a>
				</div>
			</li>
    	</ul>
		<span class="clr"></span>
    </div>
</div>
<div id="o-header-2013"><div id="header-2013" style="display:none;"></div></div>
<!--shortcut end-->

<!-- 顶通广告位 -->
<div ></div>
<!-- 顶通广告位 -->

<!-- JiPiao Header -->
<div class="gjheader">
<div id="top-nav-bd">
    <div class="top-nav top-nav-new">
        <div class="w cfix">
            <h1 class="logo">
                <a href="//trip.jd.com/" title="京东旅行"><img src="//misc.360buyimg.com/virtuals/lvyou/2015/css/i/triplogo.png" alt="旅游特价机票、火车票、酒店预订" />旅游特价机票、火车票、酒店预订- 京东</a>
                旅游特价机票、火车票、酒店预订- 京东
            </h1>
            <ul class="nav-list" id="j_trip_nav">
                <li data-http = "trip" clstag="pageclick|keycount|trip_2015032417|1"><a class="a-nav" href="//trip.jd.com/">首页</a></li>
                <li data-http = "jipiao" ><a class="a-nav" href="//jipiao.jd.com/" clstag="pageclick|keycount|trip_2015032418|1">机票<i class="nav-icon xianshihui"></i></a>
                    <div class="nav-show" id="kjp"><div class="cfix uls uls-jp"><span clstag="pageclick|keycount|trip_2015032418|1"><a href="//jipiao.jd.com/">国内机票<i class="nav-icon hot"></i></a></span><span clstag="pageclick|keycount|trip_2015032419|1"><a href="//ijipiao.jd.com/">国际/港澳台机票</a></span></div></div>
                </li>
                <li data-http = "hotel"><a class="a-nav" clstag="pageclick|keycount|trip_2015032420|1" href="//hotel.jd.com/">酒店</a>
                    <div class="nav-show" id="kjd"><div class="cfix uls uls-jd"><span clstag="pageclick|keycount|trip_2015032420|1"><a href="//hotel.jd.com/">国内 · 港澳台</a></span><span clstag="pageclick|keycount|trip_2015032421|1"><a href="//ihotel.jd.com" id="j_trip_hotel">海外酒店<i class="nav-icon hot"></i></a></span></div></div>
                </li>
                <li data-http = "visa" clstag="pageclick|keycount|trip_2015032422|1"><a class="a-nav" href="//visa.jd.com/">签证</a></li>
                <li data-http = "dujia"><a class="a-nav" clstag="pageclick|keycount|trip_2015032423|1" href="//dujia.jd.com/">度假</a>
                    <div class="nav-show" id="kdj"><div class="cfix uls uls-dj"><span clstag="pageclick|keycount|trip_2015032418|1"><a href="//dujia.jd.com/tours">跟团游</a></span><span clstag="pageclick|keycount|trip_2015032419|1"><a href="//dujia.jd.com/pkg">自助游<i class="nav-icon new" style="left:40px;"></i></a></span></div></div>
                </li>
                <li data-http = "menpiao" clstag="pageclick|keycount|trip_2015032425|1"><a class="a-nav" href="//menpiao.jd.com/">门票<i class="nav-icon new"></i></a></li>
                <li data-http = "train" clstag="pageclick|keycount|trip_2015032426|1"><a class="a-nav" href="//train.jd.com/">火车票</a></li>
                <li data-http = "youlun" clstag="pageclick|keycount|trip_2015032427|1"><a class="a-nav" href="//youlun.jd.com/">邮轮</a></li>
                <li data-http = "ct" ><a class="a-nav" href="//mice.jd.com/" clstag="pageclick|keycount|trip_2015032428|1">商旅</a>
                    <div class="nav-show" id="kct"><div class="cfix uls uls-ct"><span clstag="pageclick|keycount|201507301|1"><a href="//ct.jd.com/">差旅管理</a></span><span clstag="pageclick|keycount|201511261|3"><a href="//mice.jd.com/">会奖MICE<i class="nav-icon new"></i></a></span></div></div>
                </li>
                <li data-http = "ddwl" clstag="pageclick|keycount|trip_2015032427|1"><a class="a-nav" href="//ddwl.jd.com/">目的地<i class="nav-icon"></i></a></li>
            </ul>
            <dl class="orders" id="j_trip_order">
                <dt><span class="tx"><img id="j_trip_photo" src="//misc.360buyimg.com/virtuals/lvyou/2015/css/i/no-img.jpg"/><a class="txbg" href="//i.jd.com/user/userinfo/showImg.html" target="_blank"></a></span><strong>我的旅行订单</strong><b></b></dt>
                <dd>
                    <ul>
                        <li class="li-sp">订单信息</li>
                        <li><a href="//order.jd.com/center/list.action?t=35">我的机票订单<i></i></a></li>
                        <li><a href="//order.jd.com/center/list.action?t=39-111">我的酒店订单<i></i><em class="nav-icon hot"></em></a></li>
                        <li><a href="//dujia.jd.com/order/orderList.html">我的度假订单<i></i></a></li>
                        <li><a href="//menpiao.jd.com/order/list">我的景点订单<i></i></a></li>
                        <li><a href="//train.jd.com/order/myOrder.html">我的火车票订单<i></i></a></li>
                        <!-- <li><a href="//meeting.jd.com/order/orderCenter">我的商旅订单<i></i></a></li> -->
                    </ul>
                </dd>
            </dl>
        </div>
    </div>
    <div class="top-nav-bg"></div>
</div>
<script>
    seajs.use(location.protocol + '//misc.360buyimg.com/virtuals/lvyou/2015/js/nav.js', function() {
    })
</script>

</div><!--  /widget/header/header.vm end-->


      <!-- Main Banner begin -->
<div class="gjmb">
  
    <div class="gjfsb">
        <!-- non-multi: 358px | multi: 704px-->
        <div id="journeySearch" class="search-box" style="width: 358px;">
            <div class="search-heading clearfix">
                <h2>国际·港澳台机票查询</h2>
                <a class="gnjp-link" href="//jipiao.jd.com" clstag="pageclick|keycount|201504221|9">国内机票&nbsp;</span><i></i></a>
            </div>
            <div class="search-content clearfix">
                <!-- 搜索类型 -->
                <ul id="journeyType" class="search-form">
                    <li class="form-group">
                        <label class="rds">航班类型</label>
                        <label class="rds"><input type="radio" name="type" value="OW" id="journeyTypeOW" clstag="pageclick|keycount|201504221|1">单程</label>
                        <label class="rds"><input type="radio" checked="checked" name="type" value="RT" id="journeyTypeRT" clstag="pageclick|keycount|201504221|2">往返</label>
                        <label class="rds"><input type="radio" name="type" value="MS" id="journeyTypeMS" clstag="pageclick|keycount|201504221|3">多程&nbsp;&nbsp;<i data-ui="u-hover|&|info-show" class="ico-info info-hide" style="z-index: 5;" clstag="pageclick|keycount|201504221|4"><div class="info">多程：两段及两段以上的航程，包括
连续航线和非连续航线。例如：A-B,
B-C ; A-B,C-A  ; A-B,C-D</div></i></label>
                    </li>
                </ul>

                <!-- 单程和返程 -->
                <ul id="searchBaseForm" class="search-form" style="display: block;">
                    <li class="clearfix">
                        <label class="label">出发城市</label>
                        <div class="label-ctrl">
                            <input type="text" id="gjdepCity" class="inp-text" data-ui="u-placeholder|中文/拼音/英文" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                            <div class="gjjp-error-tip gjjp-error-w1">
                                <i></i><em>请您填写正确城市名称</em>
                            </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <label class="label">到达城市</label>
                        <div class="label-ctrl">
                            <input type="text" id="gjarrCity" class="inp-text" data-ui="u-placeholder|中文/拼音/英文" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                            <div class="gjjp-error-tip gjjp-error-w1">
                                <i></i><em>请您填写正确城市名称</em>
                            </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <label class="label">出发日期</label>
                        <div class="label-ctrl">
                            <input type="text" id="gjdepDate" readonly="readonly" class="inp-text" value="YYYY-MM-DD">
                            <div class="gjjp-error-tip gjjp-error-w1">
                                <i></i><em>请您填写出发日期</em>
                            </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <label class="label">返程日期</label>
                        <div class="label-ctrl">
                            <input type="text" id="gjarrDate" readonly="readonly" class="inp-text" value="YYYY-MM-DD">
                            <div class="gjjp-error-tip gjjp-error-w1">
                                <i></i><em>请您填写返程日期</em>
                            </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <label class="label">乘客人数</label>
                        <div class="label-ctrl">
                        <span class="label2">
                        	成人
                        </span>
                            <cite data-ui="u-select" class="form-cite form-cite2" clstag="pageclick|keycount|201504221|5">
                                <select name="" id="adtNum">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                </select>
                                <var><i></i><em data-ui="select-selected">1</em></var>
                            </cite>
                        <span class="label2 label-ml">
                        	儿童<cite class="pop-item-cite  show-age">年龄0-12岁</cite>
                        </span>
                            <cite data-ui="u-select" class="form-cite form-cite2" clstag="pageclick|keycount|201504221|6">
                                <select name="" id="chdNum">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                </select>
                                <var><i></i><em data-ui="select-selected">0</em></var>
                            </cite>
								<div class="gjjp-error-tip gjjp-error-w1" style="display: none;">
                                	<i></i><em>每成人最多可携带2个儿童登机，请您修改乘机人数量。</em>
                                </div>
                        </div>
                    </li>
                </ul>

                <!-- 多程  -->
                <div id="searchMultiFormWp" style="display:none;">
                    <ul id="searchMultiForm" class="search-form search-multiform" style="display: none;">
                        <li class="clearfix">
                            <em class="num">1</em>
                            <label class="label label-ml">出发城市</label>
                            <div class="label-ctrl">
                                <input type="text" class="inp-text gjMultiDepCity" data-ui="u-placeholder|中文/拼音/英文" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                                <div class="gjjp-error-tip">
                                    <i></i><em>请您填写正确城市名称</em>
                                </div>
                            </div>
                            <label class="label label-ml2">到达城市</label>
                            <div class="label-ctrl">
                                <input type="text" class="inp-text gjMultiArrCity" data-ui="u-placeholder|中文/拼音/英文" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                                <div class="gjjp-error-tip">
                                    <i></i><em>请您填写正确城市名称</em>
                                </div>
                            </div>
                            <label class="label label-ml2">出发时间</label>
                            <div class="label-ctrl label-ctrl2 f-error-tip">
                                <input type="text" class="inp-text gjMultiDepDate" readonly="readonly" value="">
                                <div class="gjjp-error-tip gjjp-error-w">
                                    <i></i><em>请您填写出发时间</em>
                                </div>
                            </div>
                        </li>
                        <li class="clearfix">
                            <em class="num">2</em>
                            <label class="label label-ml">出发城市</label>
                            <div class="label-ctrl">
                                <input type="text" class="inp-text gjMultiDepCity" data-ui="u-placeholder|中文/拼音/英文" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                                <div class="gjjp-error-tip">
                                    <i></i><em>请您填写正确城市名称</em>
                                </div>
                            </div>
                            <label class="label label-ml2">到达城市</label>
                            <div class="label-ctrl">
                                <input type="text" class="inp-text gjMultiArrCity" data-ui="u-placeholder|中文/拼音/英文" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                                <div class="gjjp-error-tip">
                                    <i></i><em>请您填写正确城市名称</em>
                                </div>
                            </div>
                            <label class="label label-ml2">出发时间</label>
                            <div class="label-ctrl label-ctrl2">
                                <input type="text" class="inp-text gjMultiDepDate" readonly="readonly" value="">
                                <div class="gjjp-error-tip gjjp-error-w">
                                    <i></i><em>请您填写出发时间</em>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <ul id="searchMultiFormOpt" class="search-form search-multiform" clstag="pageclick|keycount|201504221|26">
                        <li class="addbar">
                            <a class="add gj-add-routes" href="javascript:;"><b></b>添加行程</a>
                        </li>
                    </ul>
                </div>

                <!-- 单程和返程 高级搜索 -->
                <div class="search-advform" style="display: none;">
                    <div class="line"></div>
                    <ul class="search-form">
                        <li class="clearfix">
                            <label class="label">舱位等级</label>
                            <div class="label-ctrl">
                                <cite data-ui="u-select" class="form-cite">
                                    <select name="" id="seatType">
                                        <option value="ECONOMY">经济舱</option>
                                        <option value="PREMIUM_ECONOMY">超级经济舱</option>
                                        <option value="BUSINESS">公务舱</option>
                                        <option value="FIRST">头等舱</option>
                                    </select>
                                    <var><i></i><em data-ui="select-selected">经济舱</em></var>
                                </cite>
                            </div>
                        </li>
                        <li class="clearfix">
                            <label class="label">乘客类型</label>
                            <div class="label-ctrl">
                                <cite data-ui="u-select" class="form-cite">
                                    <select name="" id="passengerType">
                                        <option value="0">普通</option>
                                        <option value="2">学生</option>
                                        <option value="6">移民</option>
                                    </select>
                                    <var><i></i><em data-ui="select-selected">普通</em></var>
                                </cite>
                            </div>
                        </li>
                        <li class="clearfix">
                            <label class="label">航空公司</label>
                            <div class="label-ctrl">
                                <input id="carrier" name="carrier" type="hidden" value="">
                                <input type="text" id="carrierShow" class="inp-text" data-ui="u-placeholder|不限" autocomplete="off" value="" style="color: rgb(51, 51, 51);">
                            </div>
                        </li>
                        <li class="sp4">
                            <label class="rds2"><input type="checkbox" id="directOnly">仅查直飞</label>
                        </li>
                    </ul>
                </div>

                <!-- 多程 高级搜索 -->
                <div class="search-advform2" style="display: none;">
                    <div class="line"></div>
                    <ul class="search-form">
                        <li class="clearfix">
                            <label class="label label-ml2">舱位等级</label>
                            <div class="label-ctrl">
                                <cite data-ui="u-select" class="form-cite">
                                    <select name="" id="seatType2">
                                        <option value="ECONOMY">经济舱</option>
                                        <option value="PREMIUM_ECONOMY">超级经济舱</option>
                                        <option value="BUSINESS">公务舱</option>
                                        <option value="FIRST">头等舱</option>
                                    </select>
                                    <var><i></i><em data-ui="select-selected">经济舱</em></var>
                                </cite>
                            </div>
                            <label class="label label-ml">乘客类型</label>
                            <div class="label-ctrl">
                                <cite data-ui="u-select" class="form-cite">
                                    <select name="" id="passengerType2">
                                        <option value="0">普通</option>
                                        <option value="2">学生</option>
                                        <option value="6">移民</option>
                                    </select>
                                    <var><i></i><em data-ui="select-selected">普通</em></var>
                                </cite>
                            </div>
                            <div class="label-ctrl">
                            <span class="label2 label2-ml">
                                成人
                            </span>
                                <cite data-ui="u-select" class="form-cite form-cite2" clstag="pageclick|keycount|201504221|27">
                                    <select name="" id="adtNum2">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                    </select>
                                    <var><i></i><em data-ui="select-selected">1</em></var>
                                </cite>
                            <span class="label2 label2-ml">
                                儿童<cite class="pop-item-cite  show-age">年龄0-12岁</cite>
                            </span>
                                <cite data-ui="u-select" class="form-cite form-cite2" clstag="pageclick|keycount|201504221|28">
                                    <select name="" id="chdNum2">
                                        <option value="0">0</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                    </select>
                                    <var><i></i><em data-ui="select-selected">0</em></var>
                                </cite>
                                <div class="gjjp-error-tip gjjp-error-w1">
                                    <i></i><em>儿童不能大于成人的两倍</em>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>

                <!-- 换 -->
                <div class="return-ico" style="display: block">
                    <a href="javascript:;" class="gj-city-change">换</a>
                </div>

                <!-- 单程和返程 高级搜索和搜索按钮 | 多程的样式只需加上 search-subform2 -->
                <ul class="search-subform" style="display: block">
                    <li class="cearfix">
                        <div class="opt">
                            <a id="advSearch" href="javascript:;" clstag="pageclick|keycount|201504221|7">高级搜索<b class=""></b></a>
                        </div>
                        <div class="btn-ctrl">
                            <input type="button" class="search-btn" data-ui="u-hover|&|search-btn-hover" value="搜 索" clstag="pageclick|keycount|201504221|19">
                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <!-- Flight Search Box -->
</div>
<!-- Main Banner end -->

<!-- 工具箱 & Mini ads banner -->
<div class="w clearfix">
    <div class="group">
        <div class="toolbox">
            <table>
                <tbody>
                <tr>
                    <td><div class="prel"> <a href="http://order.jd.com/center/list.action?t=35-83" target="_blank"><i class="card"></i><span>我的机票</span></a></div></td>
                    <td><div class="prel"> <a href="/require/requirementOrder.action" target="_blank"><i class="calendar"></i><span>需求单</span></a></div></td>
                    <td><div class="prel"> <a href="/passenger/passengers.action" target="_blank"><i class="male"></i><span>常旅客信息</span></a></div></td>
                </tr>
                <tr>
                        <td>
                            <div class="prel">
                                 <a target="_blank" href="//c-nfa.jd.com/adclick?keyStr=6PQwtwh0f06syGHwQVvRO/flUa2Yuh+WcjBYaF2gLt6jFCcuMjQJc+JiPL3Swygmd
dm78GGmjWtCNp3MtAp6zyv+szfKt4CBWEUKBYEwDCBHWmoByPeXmwN+vPPmAue88vbCjJwzgisfHGxcwS/sj7rxWYVoYOtVv50b3kOpmcRSPYHTX6N0079rHxsErrCZO8kB+sSzSS0dWVpqx287jLMnQRjLX8LeruC5DQu2wwDKXBn/4XyfZBkqZDvr0dRqsYAhmxRmBoISpVNFyZRXL4a+892nOos/0aSRnf6vbMmf9HLeDipRHAKm4vcfN+U1KKFU6qVYkYEbrR18iEkgIA==&cv=2.0&url=https://sale.jd.com/act/yPI302JkXpQj.html" clstag="pageclick|keycount|201504221|33">
                                <i class="compass"></i>
                                <span>出行保障</span>
                                </a>
                            </div>
                        </td>
                        <td><div class="prel"> <a href="http://jipiao.jd.com/ticketquery/checkInProcedure.action"><i class="plane"></i><span>在线值机</span></a></div></td>
                        <td>
                            <div class="prel">
                                 <a target="_blank" href="//c-nfa.jd.com/adclick?keyStr=6PQwtwh0f06syGHwQVvRO/flUa2Yuh+WcjBYaF2gLt64i/+PoJGeen3xOk
3IU/kHxO17UKYc+ZMrmzto35gtj9uWOgzXTRwl5QzZZu3GOF9HWmoByPeXmwN+vPPmAue88vbCjJwzgisfHGxcwS/sj6qBHyXUKI/lWjWJQAAzFsfasQ+XXKQmImWSn2x9DPrVPcADfOydEgb3r/t/IOD6jebwKAFQoJNlTkPYqRWHa7QpodVXpEL15gIhF7tS9XGTIH/3PVpFk1yWjCKplUWsYiZkUIzjmhlPlHv4wTLvUHI6PS3e2iAxIftN/cIOoqdkLMz+Zwh2Sv2uEPtOqU+3QA==&cv=2.0&url=https://sale.jd.com/act/yA1VWaxd4DkthIp.html" clstag="pageclick|keycount|201504221|35">
                                <i class="board"></i>
                                <span>诈骗提示</span>
                                </a>
                            </div>
                        </td>
                </tr>
                <tr>
                    <td class="h247" colspan="3">
                        <h3> 7×24小时服务电话：400-611-5718</h3>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="gjsab">
            <ul class="clearfix">
                <li>
                    <a href="#">
                        <div class="txt">
                            <h4>神券天天抢</h4>
                            <p>超值优惠</p>
                        </div>
                        <img width="130" height="160" src="" alt=""/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="txt">
                            <h4>京东百元购</h4>
                            <p>超值优惠</p>
                        </div>
                        <img width="130" height="160" src="" alt=""/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="txt">
                            <h4>顺手领签证</h4>
                            <p>超值优惠</p>
                        </div>
                        <img width="130" height="160" src="" alt=""/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="txt">
                            <h4>旅游大放送</h4>
                            <p>超值优惠</p>
                        </div>
                        <img width="130" height="160" src="" alt=""/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="txt">
                            <h4>留学看这里</h4>
                            <p>超值优惠</p>
                        </div>
                        <img width="130" height="160" src="" alt=""/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="txt">
                            <h4>特惠商务舱</h4>
                            <p>超值优惠</p>
                        </div>
                        <img width="130" height="160" src="" alt=""/>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- 往返|单程 begin -->
<div class="w">
    <!-- GuoJiHangXian = gjhx -->
    <!-- 往返 -->
    <div class="gjtab gjhx wangfan"> 
    </div>
    <!-- 单程  -->
    <div class="gjtab gjhx gjonly"> 
    </div>
    <!-- 实际价格提醒  -->
  	<div style="text-align:right;font-size:12px;">航班价格以实际查询为准</div>	  
  	
   </div>
<!-- 往返|单程 end -->

<!-- 热门主题 begin -->
<div class="w">
    <div class="rmzt">
        <div class="rmzt-hd">
            <h2 class="clearfix"><div class="title">热门主题</div><div class="slogan">总有你想要的</div></h2>
        </div>
        <div class="rmzt-bd">
            <ul>
                <div class="overflow-hide">
                    <li>
                        <a href="#">
                            <div class="txt">
                                <h4>扫货季</h4>
                                <p class="mid">扫货圣地航线</p>
                                <p>低至 ¥1299</p>
                            </div>
                            <img src="" alt=""/>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="txt">
                                <h4>吃货天堂</h4>
                                <p class="mid">世界各地美食</p>
                                <p>航线快快走</p>
                            </div>
                            <img src="" alt=""/>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="txt">
                                <h4>海岛游</h4>
                                <p class="mid">海岛度假圣地</p>
                                <p>低至 ¥1299</p>
                            </div>
                            <img src="" alt=""/>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="txt">
                                <h4>扫货季</h4>
                                <p class="mid">扫货圣地航线</p>
                                <p>¥1299 起</p>
                            </div>
                            <img src="" alt=""/>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="txt">
                                <h4>反季旅行</h4>
                                <p class="mid">京东特供</p>
                                <p>最低 ¥1299</p>
                            </div>
                            <img src="" alt=""/>
                        </a>
                    </li>
                </div>
            </ul>
        </div>
    </div>
</div>
<!-- 热门主题 end -->

<!-- 品牌特供 begin -->
<div class="w">
    <div class="pptg">
        <h2 class="clearfix"><div class="title">品牌特供</div><div class="slogan">专属你的品质服务</div></h2>
        <div class="gjscroll" data-ui="u-slide|6|&|&|&|disabled">
            <a class="prev ctrl" data-ui="btn-prev"><b></b></a>
            <a class="next ctrl" data-ui="btn-next"><b></b></a>
            <div class="gjscroll-list">
                <ul class="brand" data-ui="slide-wrap">
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">299</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">999</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">299</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">999</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">299</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">999</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">299</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">999</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <!-- <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">299</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">999</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">299</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li>
                    <li data-ui="slide-item">
                        <a class="href-wrap" href="#"></a>
                        <div class="p-img">
                            <img width="193" height="176" class="err-product" src="" alt="">
                        </div>
                        <div class="p-price clearfix">
                            <div class="left">
                                <span class="poster">国航春节抄底价</span>
                            </div>
                            <div class="right">
                                <span class="symbol">¥</span>
                                <span class="price">999</span>
                                <span class="since">起</span>
                            </div>
                        </div>
                    </li> -->
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- 品牌特供 end -->

<!-- Footer Links begin -->
<div class="w">
    </div>
<!-- Footer links end -->




<!-- Global service and footer-->

    <!--  /widget/service/service.vm -->
<!--service start-->
<div id="service-2017">
	<div class="w">
		<ol class="slogen">
			<li class="item fore1">
				<i>多</i>品类齐全，轻松购物
			</li>
			<li class="item fore2">
				<i>快</i>多仓直发，极速配送
			</li>
			<li class="item fore3">
				<i>好</i>正品行货，精致服务
			</li>
			<li class="item fore4">
				<i>省</i>天天低价，畅选无忧
			</li>
		</ol>
	</div>
	<div class="jd-help">
		<div class="w">
			<div class="wrap">
				<dl class="fore1">
					<dt>购物指南</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-29.html">购物流程</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-151.html">会员介绍</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-297.html">生活旅行/团购</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue.html">常见问题</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-136.html">大家电</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/index.html">联系客服</a></dd>
				</dl>
				<dl class="fore2">		
					<dt>配送方式</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-81-100.html">上门自提</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-81.html">211限时达</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/103-983.html">配送服务查询</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/109-188.html">配送费收取标准</a></dd>				
					<dd><a target="_blank" href="//help.joybuy.com/help/question-list-201.html">海外配送</a></dd>
				</dl>
				<dl class="fore3">
					<dt>支付方式</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-172.html">货到付款</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-173.html">在线支付</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-176.html">分期付款</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-174.html">邮局汇款</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-175.html">公司转账</a></dd>
				</dl>
				<dl class="fore4">		
					<dt>售后服务</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/321-981.html">售后政策</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-132.html">价格保护</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/130-978.html">退款说明</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//myjd.jd.com/repair/repairs.action">返修/退换货</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-50.html">取消订单</a></dd>
				</dl>
				<dl class="fore5">
					<dt>特色服务</dt>	
					<dd><a target="_blank" href="//help.jd.com/user/issue/list-133.html">夺宝岛</a></dd>
					<dd><a target="_blank" href="//help.jd.com/user/issue/list-134.html">DIY装机</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//fuwu.jd.com/">延保服务</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//o.jd.com/market/index.action">京东E卡</a></dd>				
					<dd><a rel="nofollow" target="_blank" href="//mobile.jd.com/">京东通信</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//s.jd.com/">京东JD+</a></dd>
				</dl>
				<span class="clr"></span>
			</div>
		</div>
	</div>
</div>
<!--service end-->
<!--/ /widget/service/service.vm -->

<!--  /widget/footer/footer.vm -->
<!--footer start-->
<div id="footer-2017">
	<div class="w">
		<div class="copyright_links">
			<p>
				<a href="//about.jd.com" target="_blank">关于我们</a><span class="copyright_split">|</span>
				<a href="//about.jd.com/contact/" target="_blank">联系我们</a><span class="copyright_split">|</span>
				<a href="//help.jd.com/user/custom.html" target="_blank">联系客服</a><span class="copyright_split">|</span>
				<a href="//vc.jd.com/cooperation.html" target="_blank">合作招商</a><span class="copyright_split">|</span>
				<a href="//helpcenter.jd.com/venderportal/index.html" target="_blank">商家帮助</a><span class="copyright_split">|</span>
				<a href="//jzt.jd.com" target="_blank">营销中心</a><span class="copyright_split">|</span>
				<a href="//app.jd.com/" target="_blank">手机京东</a><span class="copyright_split">|</span>
				<a href="//club.jd.com/links.aspx" target="_blank">友情链接</a><span class="copyright_split">|</span>
				<a href="//media.jd.com/" target="_blank">销售联盟</a><span class="copyright_split">|</span>
				<a href="//club.jd.com/" target="_blank">京东社区</a><span class="copyright_split">|</span>
				<a href="//sale.jd.com/act/FTrWPesiDhXt5M6.html" target="_blank">风险监测</a><span class="copyright_split">|</span>
				<a href="//about.jd.com/privacy/" target="_blank">隐私政策</a><span class="copyright_split">|</span>
				<a href="//gongyi.jd.com" target="_blank">京东公益</a><span class="copyright_split">|</span>
				<a href="//en.jd.com/" target="_blank">English Site</a><span class="copyright_split">|</span>
				<a href="//corporate.jd.com/" target="_blank">Media & IR</a>
			</p>
		</div>
		<div class="copyright_info">
			<p>
				<a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11000002000088" target="_blank">京公网安备 11000002000088号</a><span class="copyright_split">|</span><span>京ICP证070359号</span><span class="copyright_split">|</span>
				<a href="//img14.360buyimg.com/da/jfs/t256/349/769670066/270505/3b03e0bb/53f16c24N7c04d9e9.jpg" target="_blank">互联网药品信息服务资格证编号(京)-经营性-2014-0008</a><span class="copyright_split">|</span><span>新出发京零 字第大120007号</span></p>
			<p><span>互联网出版许可证编号新出网证(京)字150号</span><span class="copyright_split">|</span>
				<a href="//sale.jd.com/act/pQua7zovWdJfcIn.html" target="_blank">出版物经营许可证</a><span class="copyright_split">|</span>
				<a href="//misc.360buyimg.com/wz/wlwhjyxkz.jpg" target="_blank">网络文化经营许可证京网文[2014]2148-348号</a><span class="copyright_split">|</span><span>违法和不良信息举报电话：4006561155</span></p>
			<p><span class="copyright_text">Copyright &copy; 2004 - <em id="copyright_year">2018</em>  京东JD.com 版权所有</span><span class="copyright_split">|</span><span>消费者维权热线：4006067733</span>
				<a href="//sale.jd.com/act/7Y0Rp81MwQqc.html" target="_blank" class="copyright_license">经营证照</a>
				<span class="copyright_split">|</span>
				<span>(京)网械平台备字(2018)第00003号</span>
				<span class="copyright_split">|</span>
				<a href="//storage.jd.com/imgtools/cbdaa22553-dccaf290-d1af-11e8-a840-89f99f5f0056.jpeg" target="_blank" class="mod_business_license">营业执照</a>
			</p>
			<p class="mod_copyright_inter">
				<a class="mod_copyright_inter_lk" href="//www.joybuy.com/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0501"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_global"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.jd.ru/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0502"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_rissia"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.jd.id/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0503"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_indonesia"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.joybuy.es/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0504"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_spain"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.jd.co.th/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0505"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_thailand"></i><span class="languagefont"></span></a>
			</p>
			<p><span>京东旗下网站：</span>
				<a href="https://www.jdpay.com/" target="_blank">京东钱包</a><span class="copyright_split">|</span>
				<a href="http://www.jcloud.com" target="_blank">京东云</a>
			</p>
		</div>
		<p class="copyright_auth">
			<script type="text/JavaScript">function CNNIC_change(eleId){var str= document.getElementById(eleId).href;var str1 =str.substring(0,(str.length-6));str1+=CNNIC_RndNum(6);
				document.getElementById(eleId).href=str1;}function CNNIC_RndNum(k){var rnd=""; for (var i=0;i
				< k;i++) rnd+=Math.floor(Math.random()*10); return rnd;};(function(){var d=new Date;document.getElementById(
				 "copyright_year").innerHTML=d.getFullYear()})();</script>
					<a id="urlknet" class="copyright_auth_ico copyright_auth_ico_2" onclick="CNNIC_change('urlknet')" oncontextmenu="return false;"
					 name="CNNIC_seal" href="https://ss.knet.cn/verifyseal.dll?sn=2008070300100000031&ct=df&pa=294005" target="_blank">可信网站信用评估</a>
					<a class="copyright_auth_ico copyright_auth_ico_3" href="http://www.cyberpolice.cn/" target="_blank">网络警察提醒你</a>
					<a class="copyright_auth_ico copyright_auth_ico_4" href="https://search.szfw.org/cert/l/CX20120111001803001836" target="_blank">诚信网站</a>
					<a class="copyright_auth_ico copyright_auth_ico_5" href="http://www.12377.cn" target="_blank">中国互联网举报中心</a>
					<a class="copyright_auth_ico copyright_auth_ico_6" href="http://www.12377.cn/node_548446.htm" target="_blank">网络举报APP下载</a>
		</p>
	</div>
</div>
<!--footer end-->
<!--/ /widget/footer/footer.vm -->

<!-- Airlines suggest hot layer -->
<div class="ac_results recommend recommendcarrier" id="forCarrierShow" style="width:300px;">
    <div class="gray ac_result_tip" id="carrierHotall">
        <a href="javascript:;" data="" showname="不限" >不限</a><br/>
    </div>
    <ul  id="carrierHot" class="fn" >
    </ul>
</div>


<script src="//misc.360buyimg.com/virtuals/ijipiao/2.0/js/data/citysnew.js"></script>

<script charset="utf-8" src="//misc.360buyimg.com/virtuals/ui/??popui.js,jcal.js,citySuggest.js,popLayer.js,cityLayer.js"></script>

<script charset="utf-8" src="//misc.360buyimg.com/virtuals/ijipiao/2.0/js/index/gjsuggest.js"></script>

<script charset="utf-8" src="//misc.360buyimg.com/virtuals/ijipiao/2.0/js/index.js" ></script>
<!-- 新浪微博关注 -->
<script src="//tjs.sjs.sinajs.cn/open/api/js/wb.js" type="text/javascript" charset="utf-8"></script>
<!-- clstag埋点引用 -->
<script type="text/javascript"> (function () { var e=document.createElement('script');e.type='text/javascript';e.async=true; e.src=('https:'==document.location.protocol?'https://cscssl':'http://csc')+'.jd.com/wl.js'; var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s); })(); </script>
</body>
</html>