<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>试用中心 试用报告</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="shortcut icon" href="//www.jd.com/favicon.ico" type="image/x-icon"/>
    <link type="text/css" rel="stylesheet"  href="//misc.360buyimg.com/jdf/1.0.0/unit/??ui-base/1.0.0/ui-base.css,shortcut/2.0.0/shortcut.css,global-header/1.0.0/global-header.css,myjd/2.0.0/myjd.css,nav/2.0.0/nav.css,shoppingcart/2.0.0/shoppingcart.css,global-footer/5.0.0/global-footer.css,service/5.0.0/service.css"/>
    <script type="text/javascript">window.pageConfig = {compatible: false, navId: "report"}; </script>
    <script type="text/javascript" src="//misc.360buyimg.com/??jdf/lib/jquery-1.6.4.js,jdf/1.0.0/unit/base/1.0.0/base.js"></script>
    <link type="text/css" rel="stylesheet" href="//static.360buyimg.com/webstatic/try/1.0.2/widget/??common/common.css,try.report/try.report.css" source="widget"/>
</head>
<body class="root61">
<div id="shortcut-2014">
	<div class="w">
		<ul class="fl" clstag="shangpin|keycount|topitemnormal|a01">
			<li class="dorpdown" id="ttbar-mycity" style="display:none"></li>
		</ul>
		<ul class="fr">
			<li class="fore1" id="ttbar-login" clstag="shangpin|keycount|topitemnormal|a02">
				<a target="_blank" href="javascript:login();" class="link-login">你好，请登录</a>
				&nbsp;&nbsp;
				<a href="javascript:regist();" class="link-regist style-red">免费注册</a>
			</li>
			<li class="spacer"></li>
			<li class="fore2"  clstag="shangpin|keycount|topitemnormal|a03">
				<div class="dt">
					<a target="_blank" href="//order.jd.com/center/list.action">我的订单</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore3 dorpdown" id="ttbar-myjd" clstag="shangpin|keycount|topitemnormal|b04">
				<div class="dt cw-icon">
					<i class="ci-right"><s>◇</s></i>
					<a target="_blank" href="//home.jd.com/">我的京东</a>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore4" clstag="shangpin|keycount|topitemnormal|a04">
				<div class="dt">
					<a target="_blank" href="//vip.jd.com/">京东会员</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore5"  clstag="shangpin|keycount|topitemnormal|a05">
				<div class="dt">
					<a target="_blank" href="//b.jd.com/">企业采购</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore6 dorpdown" id="ttbar-apps" clstag="shangpin|keycount|topitemnormal|a06">
				<div class="dt cw-icon">
					<i class="ci-left"></i>
					<i class="ci-right"><s>◇</s></i>
					<a target="_blank" href="//app.jd.com/">手机京东</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore7 dorpdown" id="ttbar-atte" clstag="shangpin|keycount|topitemnormal|a09">
				<div class="dt cw-icon">
					<i class="ci-right"><s>◇</s></i>关注京东
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore8 dorpdown" id="ttbar-serv" clstag="shangpin|keycount|topitemnormal|a07">
				<div class="dt cw-icon">
					<i class="ci-right"><s>◇</s></i>客户服务
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore9 dorpdown" id="ttbar-navs" clstag="shangpin|keycount|topitemnormal|a08">
				<div class="dt cw-icon">
					<i class="ci-right"><s>◇</s></i>网站导航
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
		</ul>
		<span class="clr"></span>
	</div>
</div><!-- #shortcut-2014 -->
<div class="w">
	<div id="logo-2014">
		<a href="//www.jd.com/" clstag="shangpin|keycount|topitemnormal|b01" class="logo">京东</a>
		<img src="//static.360buyimg.com/webstatic/try/1.0.2/css/i/try-logo-new.jpg" width="198" height="41" class="try-logo" alt="京东试用">
	</div>
	<div id="settleup-2014" class="dorpdown">
		<div class="cw-icon">
			<i class="ci-left"></i>
			<i class="ci-right">&gt;</i>
			<a target="_blank" clstag="shangpin|keycount|topitemnormal|b05" href="//cart.jd.com/cart/cart.html">我的购物车</a>
		</div>
		<div class="dorpdown-layer">
			<div class="spacer"></div>
			<div id="settleup-content">
				<span class="loading"></span>
			</div>
		</div>
	</div>
	<div id="hotwords"></div>
	<span class="clr"></span>
</div>
<div id="nav-2014">
	<div class="border-bottom"></div>
	<div class="w nav" style="position:relative;">
		<ul id="navitems-2014">
			<li id="nav-home"><a href="//try.jd.com/">试用首页</a></li>
			<li id="nav-posttry" clstag="secondtype|keycount|try|DH-FY"><a target="_blank" href="//try.jd.com/list/postlist.action">付邮试用</a></li>
			<li id="nav-lightning" clstag="secondtype|keycount|try|DH-SDS"><a target="_blank" href="//try.jd.com/list/lightning.action">闪电试</a></li>
			<li id="nav-report" clstag="secondtype|keycount|try|DH-BG"><a target="_blank" href="//try.jd.com/report-details/reportlist.action">试用报告</a></li>
			<div class="border-bottom"></div>
		</ul>
	</div>
	<div id="treasure"></div>
	<span class="clr"></span>
</div>
</div><!-- #nav-2014 -->
<!-- header end -->
<script type="text/javascript">
	(function () {
		if (pageConfig.navId) {
			var object = document.getElementById("nav-" + pageConfig.navId);
			if (object)object.className += " curr";
		}
	})();
</script>
<div class="w" id="my-tryout">
	<dl>
		<dt><a href="//try.jd.com/myTrial/myTrial.action"><b></b>我的试用<b class="b2"></b></a></dt>
		<dd><a href="//try.jd.com/myTrial/myTrial.action">申请中</a>|<a href="//try.jd.com/myTrial/myTrial.action?tab=succ">申请成功</a>|<a href="//try.jd.com/myTrial/myTrial.action?tab=fail">申请失败</a></dd>
	</dl>
</div>
<div class="j-content">
    <div class="j-banner w">
        <img src="//static.360buyimg.com/webstatic/try/1.0.1/css/i/report-banner.jpg" alt=""/>
    </div>
    <div class="nav w">
        <ul>
            <li data-cid="0" class="curr">
                <a href="javascript:;">
                    <i class="n1"></i>
                    <span>全部</span>
                </a>
            </li>
            <li data-cid="737">
                <a href="javascript:;">
                    <i class="n6"></i>
                    <span>大小家电</span>
                </a>
            </li>
            <li data-cid="670,652,9987">
                <a href="javascript:;">
                    <i class="n7"></i>
                    <span>潮流3C</span>
                </a>
            </li>
            <li data-cid="1320">
                <a href="javascript:;">
                    <i class="n8"></i>
                    <span>食品饮料</span>
                </a>
            </li>
            <li data-cid="1713,4053">
                <a href="javascript:;">
                    <i class="n4"></i>
                    <span>图书</span>
                </a>
            </li>
            <li data-cid="12218">
                <a href="javascript:;">
                    <i class="n5"></i>
                    <span>生鲜</span>
                </a>
            </li>
            <li data-cid="1319,6233">
                <a href="javascript:;">
                    <i class="n9"></i>
                    <span>母婴玩具</span>
                </a>
            </li>
            <li data-cid="1316">
                <a href="javascript:;">
                    <i class="n2"></i>
                    <span>个护化妆</span>
                </a>
            </li>
            <li data-cid="6728">
                <a href="javascript:;">
                    <i class="n3"></i>
                    <span>汽车用品</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="mc clearfix w" id="container">
        <div class="b-list-container clearfix">
                                                        <div class="b-list b-list1">
                        <div class="b-item">
                            <div class="img">
                                <a href="//try.jd.com/report/5bcaf3c8bc8a2d1be32986c1.html" target="_blank">
                                    <img src="//img10.360buyimg.com/trial/jfs/t1/9846/36/484/236089/5bcaf3c8E4c738ee7/db848cd40b70e8c6.jpg" alt="首先特别感谢京东平台给了我这次试用机会，耶丽娅车厘子精萃护齿牙膏，产妇专用，食品及原料用的安全放心，不添加氟配方，包装高大上，自用送人都很方便。发货速度也超级快😊">
                                </a>
                            </div>
                            <div class="head">
                                <div class="user-head">
                                    <img src="//storage.360buyimg.com/i.imageUpload/6a645f3464373366393563383761613631353232333835363531353235_sma.jpg"></div>
                                <div class="user-name">j***6</div>
                                <div class="user-star">
                                    试用评价：<i class="star5"></i>
                                </div>
                            </div>
                            <div class="pl">
                                <a href="//try.jd.com/report/5bcaf3c8bc8a2d1be32986c1.html" target="_blank">
                                    首先特别感谢京东平台给了我这次试用机会，耶丽娅车厘子精萃护齿牙膏，产妇专用，食品及原料用的安全放心，不添加氟配方，包装高大上，自用送人都很方便。发货速度也超级快😊
                                </a>
                            </div>
                        </div>
                    </div>
                                        <div class="b-list b-list2">
                        <div class="b-item">
                            <div class="img">
                                <a href="//try.jd.com/report/5bcaf2c36f055a7274fc71ed.html" target="_blank">
                                    <img src="//img10.360buyimg.com/trial/jfs/t1/3299/16/10325/233390/5bcaf139Ee4068477/5b06a4f2af562781.jpg" alt="非常感谢“兴煜旭宠物用品专营店”提供的力狼【LILANG】海洋鱼味猫粮 试用体验活动。商家服务很好发货速度很快，力狼猫粮提高适口性的同时为爱宠提供更多优质蛋白。科学配比多种优质天然食材，有效提高消化吸收率，均衡营养。">
                                </a>
                            </div>
                            <div class="head">
                                <div class="user-head">
                                    <img src="//storage.360buyimg.com/i.imageUpload/746a636f696f31353339383731303830353634_sma.jpg"></div>
                                <div class="user-name">t***o</div>
                                <div class="user-star">
                                    试用评价：<i class="star5"></i>
                                </div>
                            </div>
                            <div class="pl">
                                <a href="//try.jd.com/report/5bcaf2c36f055a7274fc71ed.html" target="_blank">
                                    非常感谢“兴煜旭宠物用品专营店”提供的力狼【LILANG】海洋鱼味猫粮 试用体验活动。商家服务很好发货速度很快，力狼猫粮提高适口性的同时为爱宠提供更多优质蛋白。科学配比多种优质天然食材，有效提高消化吸收率，均衡营养。
                                </a>
                            </div>
                        </div>
                    </div>
                                        <div class="b-list b-list3">
                        <div class="b-item">
                            <div class="img">
                                <a href="//try.jd.com/report/5bcaec307824ff70681866eb.html" target="_blank">
                                    <img src="//img10.360buyimg.com/trial/jfs/t1/6112/12/965/55068/5bcaea71Ed948ffd8/aa83b9e9eb6a87fd.jpg" alt="试用了一下非常满意!总结一下：1、收纳包的容量很大，一般旅行需要随身携带的牙膏，毛巾，化妆盒之类的生活用品都可以装下；2、这个收纳包十分透气。正面采用了网孔结构。这样做的好处是，哪怕你短时间装一些有点潮湿的物品，也不用担心会霉变；3、方便清洗，经久耐用。这个收纳包用的涤纶和尼龙材料，涤纶和尼龙都是耐用、耐洗的材料，保证了这个收纳袋能长时间使用。4、拉链开合十分顺畅。">
                                </a>
                            </div>
                            <div class="head">
                                <div class="user-head">
                                    <img src="//storage.360buyimg.com/i.imageUpload/6a645f3666396464643137323765356331353233393534303430343933_sma.jpg"></div>
                                <div class="user-name">j***c</div>
                                <div class="user-star">
                                    试用评价：<i class="star5"></i>
                                </div>
                            </div>
                            <div class="pl">
                                <a href="//try.jd.com/report/5bcaec307824ff70681866eb.html" target="_blank">
                                    试用了一下非常满意!总结一下：1、收纳包的容量很大，一般旅行需要随身携带的牙膏，毛巾，化妆盒之类的生活用品都可以装下；2、这个收纳包十分透气。正面采用了网孔结构。这样做的好处是，哪怕你短时间装一些有点潮湿的物品，也不用担心会霉变；3、方便清洗，经久耐用。这个收纳包用的涤纶和尼龙材料，涤纶和尼龙都是耐用、耐洗的材料，保证了这个收纳袋能长时间使用。4、拉链开合十分顺畅。
                                </a>
                            </div>
                        </div>
                    </div>
                                        <div class="b-list b-list4">
                        <div class="b-item">
                            <div class="img">
                                <a href="//try.jd.com/report/5bcaeb10cbd6f968a263cd52.html" target="_blank">
                                    <img src="//img10.360buyimg.com/trial/jfs/t1/310/18/10671/95632/5bcae906Edf642601/25f9c9a11f8ad04d.jpg" alt="试用了这款减肥咖啡，没有节食和运动，就轻轻松松的瘦了3斤多，刚开始服用的时候最担心的就是害怕有副作用，对身体有害什么的，结果服用了这么长时间也没有出现不良反应，没有拉肚子，没有头晕，没有恶心和其他异常一切都很正常所以现在我对这款减肥产品越来越有兴趣。">
                                </a>
                            </div>
                            <div class="head">
                                <div class="user-head">
                                    <img src="//storage.360buyimg.com/i.imageUpload/31383331343134313130385f7031343834363536303333373339_sma.jpg"></div>
                                <div class="user-name">1***p</div>
                                <div class="user-star">
                                    试用评价：<i class="star5"></i>
                                </div>
                            </div>
                            <div class="pl">
                                <a href="//try.jd.com/report/5bcaeb10cbd6f968a263cd52.html" target="_blank">
                                    试用了这款减肥咖啡，没有节食和运动，就轻轻松松的瘦了3斤多，刚开始服用的时候最担心的就是害怕有副作用，对身体有害什么的，结果服用了这么长时间也没有出现不良反应，没有拉肚子，没有头晕，没有恶心和其他异常一切都很正常所以现在我对这款减肥产品越来越有兴趣。
                                </a>
                            </div>
                        </div>
                    </div>
                                            </div>
        <div class="notice">
            <span>没有更多试用报告了</span>
        </div>
    </div>
</div>
<div id="GLOBAL_FOOTER" type="common_config2"></div>
<script type="text/javascript" src="//static.360buyimg.com/webstatic/try/1.0.2/widget/try.report/try.waterfall.js"></script>
<script type="text/javascript" src="//static.360buyimg.com/webstatic/try/1.0.2/widget/??common/common.js,try.report/try.report.js" source="widget"></script>
    <script type="text/javascript" src="//wl.jd.com/wl.js"></script>
</body>
</html>
