<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>试用列表</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="shortcut icon" href="//www.jd.com/favicon.ico" type="image/x-icon"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="canonical" href="//try.jd.com/"/>
    <link rel="dns-prefetch" href="//misc.360buyimg.com"/>
    <link rel="dns-prefetch" href="//static.360buyimg.com"/>
    <link rel="dns-prefetch" href="//img10.360buyimg.com"/>
    <link rel="dns-prefetch" href="//img11.360buyimg.com"/>
    <link rel="dns-prefetch" href="//img13.360buyimg.com"/>
    <link rel="dns-prefetch" href="//img12.360buyimg.com"/>
    <link rel="dns-prefetch" href="//img14.360buyimg.com"/>
    <link rel="dns-prefetch" href="//img30.360buyimg.com"/>
    <link rel="dns-prefetch" href="//p.3.cn"/>
    <script>
        var pageConfig = {
            "jdfVersion": '2.0.0',
            "pagination":{
                "total":6140,
                "pageSize":20,
                "page":1,
                "pages":307
            },
            "url":"/activity/getActivityList?page=1"
        };
    </script>
    <link type="text/css" rel="stylesheet"
          href="//misc.360buyimg.com/jdf/1.0.0/unit/??ui-base/1.0.0/ui-base.css,shortcut/2.0.0/shortcut.css,global-header/1.0.0/global-header.css,myjd/2.0.0/myjd.css,nav/2.0.0/nav.css,shoppingcart/2.0.0/shoppingcart.css,global-footer/5.0.0/global-footer.css,service/5.0.0/service.css"/>
    <script type="text/javascript"
            src="//misc.360buyimg.com/??jdf/lib/jquery-1.6.4.js,jdf/1.0.0/unit/base/1.0.0/base.js"></script>
    <link type="text/css" rel="stylesheet" href="//misc.360buyimg.com/mall/try/1.0.0/widget/??head/head.css,common/common.css,selector/selector.css,goods-list/goods-list.css" source="widget"/>
    <script type="text/javascript" src="//misc.360buyimg.com/mall/try/1.0.0/widget/??common/common.js,selector/selector.js" source="widget"></script>
</head>
<body class="root61">
<!-- #shortcut-2014 -->
<div id="shortcut-2014">
    <div class="w">
        <ul class="fl"><li id="ttbar-home"><a href="//www.jd.com" target="_blank">返回京东首页</a></li></ul>
        <ul class="fr">
            <li class="fore1" id="ttbar-login" clstag="shangpin|keycount|topitemnormal|a02">
                <a target="_blank" href="javascript:login();" class="link-login">你好，请登录</a>
                &nbsp;&nbsp;
                <a href="javascript:regist();" class="link-regist style-red">免费注册</a>
            </li>
            <li class="spacer"></li>
            <li class="fore2"  clstag="shangpin|keycount|topitemnormal|a03">
                <div class="dt">
                    <a target="_blank" href="//order.jd.com/center/list.action">我的订单</a>
                </div>
            </li>
            <li class="spacer"></li>
            <li class="fore3 dorpdown" id="ttbar-myjd" clstag="shangpin|keycount|topitemnormal|b04">
                <div class="dt cw-icon">
                    <i class="ci-right"><s>◇</s></i>
                    <a target="_blank" href="//home.jd.com/">我的京东</a>
                </div>
                <div class="dd dorpdown-layer"></div>
            </li>
            <li class="spacer"></li>
            <li class="fore4" clstag="shangpin|keycount|topitemnormal|a04">
                <div class="dt">
                    <a target="_blank" href="//vip.jd.com/">京东会员</a>
                </div>
            </li>
            <li class="spacer"></li>
            <li class="fore5"  clstag="shangpin|keycount|topitemnormal|a05">
                <div class="dt">
                    <a target="_blank" href="//b.jd.com/">企业采购</a>
                </div>
            </li>
            <li class="spacer"></li>
            <li class="fore6 dorpdown" id="ttbar-apps" clstag="shangpin|keycount|topitemnormal|a06">
                <div class="dt cw-icon">
                    <i class="ci-left"></i>
                    <i class="ci-right"><s>◇</s></i>
                    <a target="_blank" href="//app.jd.com/">手机京东</a>
                </div>
            </li>
            <li class="spacer"></li>
            <li class="fore7 dorpdown" id="ttbar-atte" clstag="shangpin|keycount|topitemnormal|a09">
                <div class="dt cw-icon">
                    <i class="ci-right"><s>◇</s></i>关注京东
                </div>
            </li>
            <li class="spacer"></li>
            <li class="fore8 dorpdown" id="ttbar-serv" clstag="shangpin|keycount|topitemnormal|a07">
                <div class="dt cw-icon">
                    <i class="ci-right"><s>◇</s></i>客户服务
                </div>
                <div class="dd dorpdown-layer"></div>
            </li>
            <li class="spacer"></li>
            <li class="fore9 dorpdown" id="ttbar-navs" clstag="shangpin|keycount|topitemnormal|a08">
                <div class="dt cw-icon">
                    <i class="ci-right"><s>◇</s></i>网站导航
                </div>
                <div class="dd dorpdown-layer"></div>
            </li>
        </ul>
        <span class="clr"></span>
    </div>
</div>
<!-- #shortcut-2014 -->
<!-- #Header -->
<div class="w">
    <div id="logo-2014">
       <a href="//try.jd.com" clstag="secondtype|keycount|try|LOGO">
            <img src="//static.360buyimg.com/devfe/try-new//1.0.0/css/i/logo_03.png" width="138" height="35" class="l-logo" alt="京东试用">
           <img src="//static.360buyimg.com/devfe/try-new/1.0.0/css/i/r-logo_03.png" width="124" height="21" class="r-logo" alt="京东试用">
       </a>
    </div>
    <div id="search-2014">
        <ul id="shelper" class="hide" style="display: none;"></ul>
        <div class="form" style="display:none;"><input type="text" onkeydown="javascript:if(event.keyCode==13) search('key');" autocomplete="off" id="key" accesskey="s" class="text" style="color: rgb(228,57,60)">
            <button onclick="search('key');return false;" class="button cw-icon"><i></i>搜索</button>
        </div>
    </div>
    <div id="settleup-2014" class="dorpdown">
        <div class="cw-icon">
            <i class="ci-left"></i>
            <i class="ci-right">&gt;</i>
            <a target="_blank" href="//cart.jd.com/cart/cart.html" clstag="secondtype|keycount|try|GWC">我的购物车</a>
        </div>
        <div class="dorpdown-layer">
            <div class="spacer"></div>
            <div id="settleup-content">
                <span class="loading"></span>
            </div>
        </div>
    </div>
    <div id="hotwords"></div>
    <span class="clr"></span>
</div>
<!-- #Header -->
<!-- #Nav -->
<div id="nav-2014">
    <div class="border-bottom"></div>
    <div class="w nav" style="position:relative;">
        <ul id="navitems-2014">
            <li id="nav-home" class="curr">
                <a class="item" href="//try.jd.com/" target="_blank" clstag="secondtype|keycount|try|SY">首页</a>
            </li>
            <li id="nav-all">
                <a class="item"  href="//try.jd.com/activity/getActivityList" target="_blank" clstag="secondtype|keycount|try|QBSY">全部试用<i class="arrows"></i></a>
                <div class="box">
                    <ul class="clearfix">
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=737" target="_blank">家用电器</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=652,9987" target="_blank">手机数码</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=670" target="_blank">电脑办公</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=1620,6728,9847,9855,6196,15248" target="_blank">家居家装</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=1316" target="_blank">美妆护肤</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=1315,1672,1318,11729" target="_blank">服饰鞋包</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=1319,6233" target="_blank">母婴玩具</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=12218" target="_blank">生鲜美食</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=1713,4051,4052,4053,7191,7192,5272" target="_blank">图书音像</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=5025,6144" target="_blank">钟表奢品</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=16750" target="_blank">个人护理</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=15901" target="_blank">家庭清洁</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=1320,12259" target="_blank">食品饮料</a></li>
                        <li><a href="//try.jd.com/activity/getActivityList?page=1&cids=4938,13314,6994,9192,12473,6196,5272,12379,13678,15083,15126,15980" target="_blank">更多惊喜</a></li>
                    </ul>
                </div>
            </li>
            <li id="nav-report">
                <a class="item"  target="_blank" href="//try.jd.com/report-details/reportlist.action" target="_blank" clstag="secondtype|keycount|try|SYBG">试用报告</a>
            </li>
            <li id="nav-help">
                <a class="item"  target="_blank" href="//help.jd.com/user/issue/list-354.html" target="_blank" clstag="secondtype|keycount|try|BZZX">帮助中心</a>
            </li>
            <li id="nav-my">
                <a class="item"  href="//try.jd.com/user/myTrial" target="_blank" clstag="secondtype|keycount|try|WDSY">我的试用<i class="arrows"></i></a>
                <div class="box">
                    <ul class="clearfix">
                        <li><a href="//try.jd.com/user/myTrial" target="_blank">试用记录</a></li>
                        <li style="display:none;"><a href="javascript:;">试用报告</a></li>
                    </ul>
                </div>
            </li>
            <div class="border-bottom"></div>
        </ul>
    </div>
    <div id="treasure"></div>
    <span class="clr"></span>
</div>
<!-- #Nav -->
<div class="container" style="padding-top: 30px">
    <div class="w">
        <!--  /widget/selector/selector.vm -->
        <div id="selector" class="selector">
            <div class="top">
                                    <div class="line clearfix">
                        <dl>
                            <dt><span></span>商品分类</dt>
                            <dd>
                                <a href="/activity/getActivityList?page=1&cids=737" cids="737" clgtag="secondtype|keycount|try|SPFL-1">家用电器</a>
                                <a href="/activity/getActivityList?page=1&cids=652,9987" cids="652,9987" clgtag="secondtype|keycount|try|SPFL-2">手机数码</a>
                                <a href="/activity/getActivityList?page=1&cids=670" cids="670" clgtag="secondtype|keycount|try|SPFL-3">电脑办公</a>
                                <a href="/activity/getActivityList?page=1&cids=1620,6728,9847,9855,6196,15248" cids="1620,6728,9847,9855,6196,15248" clgtag="secondtype|keycount|try|SPFL-4">家居家装</a>
                                <a href="/activity/getActivityList?page=1&cids=1316" cids="1316" clgtag="secondtype|keycount|try|SPFL-5" >美妆护肤</a>
                                <a href="/activity/getActivityList?page=1&cids=1315,1672,1318,11729" cids="1315,1672,1318,11729"  clgtag="secondtype|keycount|try|SPFL-6">服饰鞋包</a>
                                <a href="/activity/getActivityList?page=1&cids=1319,6233" cids="1319,6233"  clgtag="secondtype|keycount|try|SPFL-7">母婴玩具</a>
                                <a href="/activity/getActivityList?page=1&cids=12218" cids="12218"  clgtag="secondtype|keycount|try|SPFL-8">生鲜美食</a>
                                <a href="/activity/getActivityList?page=1&cids=1713,4051,4052,4053,7191,7192,5272" cids="1713,4051,4052,4053,7191,7192,5272" clgtag="secondtype|keycount|try|SPFL-9">图书音像</a>
                                <a href="/activity/getActivityList?page=1&cids=5025,6144" cids="5025,6144" clgtag="secondtype|keycount|try|SPFL-10">钟表奢品</a>
                                <a href="/activity/getActivityList?page=1&cids=16750" cids="16750" clgtag="secondtype|keycount|try|SPFL-11">个人护理</a>
                                <a href="/activity/getActivityList?page=1&cids=15901" cids="15901" clgtag="secondtype|keycount|try|SPFL-12">家庭清洁</a>
                                <a href="/activity/getActivityList?page=1&cids=1320,12259" cids="1320,12259" clgtag="secondtype|keycount|try|SPFL-13">食品饮料</a>
                                <a href="/activity/getActivityList?page=1&cids=4938,13314,6994,9192,12473,6196,5272,12379,13678,15083,15126,15980" cids="4938,13314,6994,9192,12473,6196,5272,12379,13678,15083,15126,15980" clgtag="secondtype|keycount|try|SPFL-14">更多惊喜</a>
                            </dd>
                        </dl>
                        <a href="javascript:;" class="op unfold"><span>更多</span><i></i></a>
                        <!--收起的时候 <a href="javascript:;" class="op fold"><span>收起</span><i></i></a>-->
                    </div>
                                                <div class="line clearfix">
                    <dl class="clearfix">
                        <dt><span></span>试用类型</dt>
                        <dd>
                            <a href="/activity/getActivityList?page=1&activityType=1" clstag="secondtype|keycount|try|HDLX-1"><span>免费试用</span></a>
                            <a href="/activity/getActivityList?page=1&activityType=3" clstag="secondtype|keycount|try|HDLX-2"><span>闪电试</span></a>
                            <a href="/activity/getActivityList?page=1&activityType=5" clstag="secondtype|keycount|try|HDLX-3"><span>30天试用</span></a>
                        </dd>
                    </dl>
                </div>
                                                <div class="line clearfix">
                    <dl class="clearfix">
                        <dt><span></span>参与状态</dt>
                        <dd>
                            <a href="/activity/getActivityList?page=1&activityState=0" clstag="secondtype|keycount|try|HDZT-1"><span>申请中</span></a>
                            <a href="/activity/getActivityList?page=1&activityState=1" clstag="secondtype|keycount|try|HDZT-2"><span>即将开始</span></a>
                            <a href="/activity/getActivityList?page=1&activityState=-1" clstag="secondtype|keycount|try|HDZT-3"><span>申请结束</span></a>
                        </dd>
                    </dl>
                </div>
                            </div>
            <div class="h-selected">
                            </div>
        </div>
    </div>
    <div style="background-color: #f2f2f2">
        <div class="w">
            <!--  /widget/goods-list/goods-list.vm -->
            <div class="goods-list" id="goods-list">
                                    <div class="top-page clearfix">
                        <div class="f-result-sum">共<span id="J_resCount" class="num">6140</span>个试用商品</div>
                        <div id="J_topPage" class="f-pager">
                            <span class="fp-text"><b>1</b><em>/</em><i>307</i></span>
                            <a class="fp-prev disabled" href="#this">&lt;</a>
                            <a class="fp-next" href="#this">&gt;</a>
                        </div>
                    </div>
                                                    <div class="items">
                        <div class="con">
                            <ul class="clearfix" clstag="secondtype|keycount|try|LBDP">
                                                                    <li class="item" activity_id="434932" start_time="1540029600000" end_time="1540108800000" sku_id="33783366589" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t27778/137/528774737/113794/6cd8e7ad/5bb05e3cNa132c772.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">华克 美度标准港度戒指圈 手指尺寸大小测量号码数 手寸圈英度戒指圈 手指指圈测量 港度圈(中国通用)</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-33783366589">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434932.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434892" start_time="1540029600000" end_time="1540112400000" sku_id="33842583106" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t26209/90/564283035/300405/dc0226cd/5bb20930N2b3e5a22.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">专业健身跳绳成人男女性运动训练负重钢丝跳神儿童中考专用绳跳绳 黑色 3米</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>1</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-33842583106">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434892.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434891" start_time="1540029600000" end_time="1540112400000" sku_id="30295329075" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t19240/107/2287198414/459391/7fe560d1/5af0fa29N3a394be9.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">艾美仕 AiMeiShi 环保包胶六角哑铃 易清洁 男士2kg 5kg 10kg20kg家用健身器材 2kg单只【此选项无任何赠品】</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>1</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-30295329075">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434891.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434889" start_time="1540029600000" end_time="1540112400000" sku_id="34883120028" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t1/8119/4/556/219702/5bcad8dfEb5d1dba4/f8dabbb7f360bed4.png" width="130" height="130">
                                            </div>
                                            <div class="p-name">木易拾陆台灯分段LED调光床头灯学习阅读工作台灯 小号拉丝咖啡 暖色光</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-34883120028">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434889.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434885" start_time="1540029600000" end_time="1540108800000" sku_id="10419898939" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t3772/61/444438264/213995/c5faa96f/5809d646N988dd9f6.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">桃醉（Toozee） 人体润滑油 情趣按摩精油 成人 夫妻 情侣全身润滑液推背刮痧男女用 100ML</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-10419898939">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434885.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434882" start_time="1540033200000" end_time="1540116000000" sku_id="33238657138" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t27628/356/829384316/72030/3291e76f/5bbb19b7N6e40a3ab.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">【买二送一】冻疮膏止痒防冻防裂护手霜手脚耳朵脸部粗糙出血冻烂止裂冻手膏皲裂防冻霜男女士通用30g 一瓶装</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>1</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-33238657138">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434882.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434880" start_time="1540029600000" end_time="1540047600000" sku_id="31889353205" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t25939/232/860669167/463207/e44e43ed/5b7e1f8bNa8efbeea.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">易京(YJING) oppor17钢化膜蓝光手机保护贴膜 适用于OPPO R17 紫蓝光全屏透明+碳纤维后膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>20</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-31889353205">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434880.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434877" start_time="1540029600000" end_time="1540112400000" sku_id="34892678333" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t1/4898/16/10367/175670/5bcafaf0E27da5d59/b9e70a9ebf0c616b.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">蒂花之秀浪漫香水香薰衣草香氛沐浴乳1kg 家庭装沐浴露 舒眠润肤保湿 舒缓嫩滑肌肤持久留香洗澡液 自然花香沐浴露400g</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-34892678333">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434877.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434875" start_time="1540026000000" end_time="1540098000000" sku_id="33694454049" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t27163/205/420430744/213995/c5faa96f/5badf9adNbccf0509.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">桃醉（Toozee）  情趣按摩精油 成人 夫妻 情侣全身按摩推背油润滑液推背刮痧男女用品 定制款（勿拍）</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-33694454049">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434875.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434873" start_time="1540026000000" end_time="1540094400000" sku_id="34435633671" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t25864/300/2021933528/136510/e0e75f25/5bc1b510N294db846.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">桃醉（Toozee） 人体润滑油剂液 按摩油 成人情趣性爱用品水溶性润滑油 男女通用夫妻房事 定制品（勿拍）</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-34435633671">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434873.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434872" start_time="1540029600000" end_time="1540112400000" sku_id="26623565982" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t18481/321/1091353834/88926/90473cd6/5ab9a9b0Ne6b1156f.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">抖音同款一捏耳朵会动的兔子帽子气囊磁铁帽玩具可爱帽子搞怪恶搞 会动的耳朵白色 耳朵会动的兔子帽子</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-26623565982">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434872.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434862" start_time="1540026000000" end_time="1540047600000" sku_id="28098297137" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t19366/6/2423862033/478091/26a53958/5af4f296N47009c26.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">造贝(ZAOBEI) 美图v6钢化膜蓝光全屏高清手机保护贴膜 适用于美图MP1605 全屏蓝光前膜+碳纤维后膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-28098297137">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434862.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434861" start_time="1540026000000" end_time="1540047600000" sku_id="28246237507" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t21703/109/87437523/708309/5caedbdb/5afae547Nb4a9fdb8.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">造贝(ZAOBEI) oppo r9磨砂钢化膜蓝光手机保护贴膜 适用于R9/r9plus 全屏磨砂抗蓝光钢化膜+碳纤维后膜 r9(5.5英寸)</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-28246237507">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434861.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434859" start_time="1540026000000" end_time="1540047600000" sku_id="29295615757" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t20872/63/1231507711/419184/a2d933e2/5b227988Nd78aece8.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">造贝(ZAOBEI) 荣耀Play钢化膜蓝光全屏高清手机保护贴膜 适用于华为荣耀play 全屏蓝光前膜+碳纤维后膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-29295615757">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434859.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434858" start_time="1540026000000" end_time="1540044000000" sku_id="32456570454" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t1/3229/24/132/678353/5b8f79cfE4f21e691/9291e7ca25e31d5b.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">造贝(ZAOBEI) vivo x23磨砂钢化膜蓝光手机保护贴膜 全屏磨砂抗蓝光钢化膜+碳纤维后膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-32456570454">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434858.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434857" start_time="1540026000000" end_time="1540040400000" sku_id="28034137364" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t19951/96/399512179/735935/9e691194/5af287dfN9b9f03f3.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">造贝(ZAOBEI) 小米note3磨砂钢化膜蓝光手机保护贴膜 全屏磨砂抗蓝光钢化膜+碳纤维后膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-28034137364">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434857.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434853" start_time="1540026000000" end_time="1540108800000" sku_id="34884453370" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t1/890/28/10631/328940/5bcadbc1E3aaac730/55bd73d55a6f7caa.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">野渡女士内裤配套一片式背心内衣无痕三角裤女式舒适透气中低腰高弹力纯色春夏秋冬四季薄款柔软包臀底裤日韩 18005浅灰色 M/L</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-34884453370">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434853.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434850" start_time="1540026000000" end_time="1540044000000" sku_id="34023125779" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t25657/87/1646199430/605787/10f0fa67/5bb76644Nc4977aef.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">易京(YJING) iPhone xs max手机壳防摔全包硅胶保护套软壳 适用于苹果xs max 气囊透明+挂绳+软膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-34023125779">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434850.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434849" start_time="1540026000000" end_time="1540040400000" sku_id="34249243767" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t26137/352/955881244/457591/b949b622/5bbd9cc1N8e2a736d.jpg" width="130" height="130">
                                            </div>
                                            <div class="p-name">易京(YJING) vivox23手机壳防摔全包硅胶保护套软壳 适用于VIVO X23 气囊透明+挂绳+软膜</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>10</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-34249243767">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434849.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                                    <li class="item" activity_id="434844" start_time="1540026000000" end_time="1540108800000" sku_id="30936841704" sys_time="1540035124899">
                                        <div class="try-item">
                                            <div class="p-img">
                                                <img data-lazy-img="done"
                                                     src="//img30.360buyimg.com/pop/s400x400_jfs/t23422/237/1730878410/208421/4cb2e21e/5b68528bN853f14a3.png" width="130" height="130">
                                            </div>
                                            <div class="p-name">力狼 LILANG 0.5公斤益生菌幼犬粮 去泪痕 除眼屎泰迪金毛边牧沙皮犬萨摩耶贵宾犬天然狗粮</div>
                                            <div class="p-detail">
                                                <input type="hidden" class="choiceCount">
                                                <div class="t1">提供<b>5</b>份<span class="separate">|</span>已有<b class="b2">0</b>人申请
                                                </div>
                                            </div>
                                            <div class="p-price ">京东价：<span class="J-p-30936841704">暂无报价</span></div>
                                            <div class="p-bottom">
                                                <div class="cd">
                                                    <span class="detail">剩余：<b>00</b>天<b>00</b>时<b>00</b>分<b>00</b>秒</span>
                                                </div>
                                            </div>
                                            <div class="try-button">
                                                我要试用
                                            </div>
                                            <i class="apply-state"></i>
                                            <a class="link" href="//try.jd.com/434844.html" target="_blank"></a>
                                                                                            <i class="tab-icon1">闪电试</i>
                                                                                    </div>
                                    </li>
                                                            </ul>
                        </div>
                    </div>
                            </div>
            <div class="page clearfix">
                <div class="p-wrap" id="J_bottomPage" clstag="secondtype|keycount|try|YM">
                    <span class="p-num" id="pager">

                    </span>
                    <span class="p-skip">
                        <em>共<b>307</b>页&nbsp;&nbsp;到第</em>
                        <input class="input-txt" id="page_jump_num" maxlength="4" value="1"
                               onkeyup="this.value=this.value.replace(/[^0-9]/g,'');"
                               onkeydown="javascript:if(event.keyCode==13){page_jump();return false;}">
                        <em>页</em>
                        <a class="btn btn-default" href="javascript:page_jump();">确定</a>
                    </span>
                </div>
            </div>
            <!--/ /widget/goods-list/goods-list.vm -->
        </div>
    </div>
</div>
<div id="GLOBAL_FOOTER"></div>
<script type="text/javascript">
    seajs.config({
        paths: {
            'APP_ROOT': '//misc.360buyimg.com/mall/try/1.0.0',
            'WDG_ROOT': '//misc.360buyimg.com/mall/try/1.0.0/widget',
            'JDF_UI': '//misc.360buyimg.com/jdf/1.0.0/ui',
            'JDF_UNIT': '//misc.360buyimg.com/jdf/1.0.0/unit',
            'JDF_LIB': '//misc.360buyimg.com/jdf/lib',
            'JDF_UII': '//misc.360buyimg.com/jdf/2.0.0/ui'
        }
    });
    seajs.use('APP_ROOT/js/list',function(App){
        App.init();
    });
</script>
<script type="text/javascript" src="//wl.jd.com/wl.js"></script>
</body>
</html>