<div style=" margin-left: 10%;margin-top: 4%;">
<h4>《京东账户注销须知》</h4>
<p>您在申请注销流程中点击同意前，应当认真阅读《京东账户注销须知》（以下称“《注销须知》”）。</p>
<h5>请您务必审慎阅读、充分理解协议中相关条款内容，其中包括：</h5>
<h5>1、与您约定免除或限制责任的条款；</h5>
<h5>2、其他以粗体下划线标识的重要条款。</h5>
<p>如您对本《注销须知》有任何疑问，可拨打我们的客服电话400-606-5500联系客服，您也可联系在线客服或通过https://help.jd.com自助查询。</p>
<p>【特别提示】当您按照注销页面提示填写信息、阅读并同意本《注销须知》及相关条款与条件且完成全部注销程序后，即表示您已充分阅读、理解并接受本《注销须知》的全部内容。阅读本《注销须知》的过程中，如果您不同意相关任何条款和条件约定，请您立即停止账户注销程序。</p>
<h5>亲爱的京东个人消费者用户：</h5>
<p>我们在此善意地提醒您，您注销账户的行为会给您的售后维权带来诸多不便，且注销京东账户后，您的个人信息我们只会在京东商城的前台系统中去除，使其保持不可被检索、访问的状态，或对其进行匿名化处理。您知晓并理解，根据相关法律规定相关交易记录须再京东后台保存5年甚至更长的时间。</p>
<h5>1. 如果您仍执意注销账户，您的账户需同时满足以下条件：</h5>
<p style="text-indent: 0em;">（1）在最近一个月内，账户没有进行更改密码、更改绑定信息等敏感操作，账户没有被盗、被封等风险；<br>
    （2）账户在京东商城系统中无资产和虚拟权益（包括但不限于账户余额、E卡余额、京豆、优惠券等）、无拍卖保证金、无欠款；<br>
    （3）账户内无未完成的订单、服务，且所有订单完成达一年以上； <br>
    （4）在京东商城没有过使用该账户激活店铺的记录；<br>
    （5）账户无任何纠纷，包括投诉举报或被投诉举报；<br>
    （6）账户为正常使用中的账户且无任何账户被限制的记录；<br>
    （7）账户对应的京东支付账户已注销，且已妥善处理了京东支付账户下的所有问题；<br>
    （8）账户已经解除与其他网站、其他APP的授权登录或绑定关系。<br>
</p>
<h5>2. 京东账户一旦被注销将不可恢复，请您在操作之前自行备份京东账户相关的所有信息和数据。请您保存好订单商品和服务的交易凭证、票据等资料，否则您有可能须支付额外的账户和订单查询费用，或无法享受售后服务。</h5>
<p style="text-indent: 0em;">3. 如果您的京东账户同时是京东平台商家店铺的绑定账户名，您需先解除相关绑定；</p>
<p style="text-indent: 0em;">4 .在京东账户注销期间，如果您的京东账户涉及争议纠纷，包括但不限于投诉、举报、诉讼、仲裁、国家有权机关调查等，京东有权自行终止本京东账户的注销而无需另行得到您的同意。</p>
<h5>5. 注销京东账户，您将无法再使用本京东账户，也将无法找回您京东账户中及与账户相关的任何内容或信息，包括但不限于：</h5>
<p style="text-indent: 0em;">（1）您将无法登录、使用本京东账户；<br>
    （2）本京东账户的个人资料和历史信息（包括但不限于用户名、头像、购物记录、关注信息等）都将无法找回；<br>
    （3）您通过京东账户使用、授权登录或绑定京东账户后使用的京东相关或第三方的其他服务（包括但不限于京东阅读、京东云、京东金融等）的所有记录将无法找回。您将无法再登录、使用前述服务，您曾获得的余额、优惠券、积分、资格、订单、E卡及其他卡券等视为您自行放弃，将无法继续使用。您理解并同意，京东无法协助您重新恢复前述服务。请您在提交注销申请前，务必先了解您须解绑的其他相关账户信息，具体可与我们的客服联系。<br>
</p>
<h5>6. 注销本京东账户并不代表本京东账户注销前的账户行为和相关责任得到豁免或减轻。</h5>
</div>


 