<!DOCTYPE html>
<html >
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<title>网上办理乘机 </title>
<script>
	var jdpts=new Object();jdpts._st=new Date().getTime();
                window.pageConfig = {
            navId:"jipiao"
        }
        </script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script type="text/javascript" src="//misc.360buyimg.com/??jdf/1.0.0/unit/base/5.0.0/base.js,jdf/lib/jquery-1.6.4.js"></script>
	    <link type="text/css" rel="stylesheet" href="//storage.360buyimg.com/jipiao/static/base.css?t=20130827"/>
    <link type="text/css" rel="stylesheet" href="//misc.360buyimg.com/virtuals/lib/skin/2012/virtuals.core.css?t=20120918"/>
    <script type="text/javascript" src="//misc.360buyimg.com/lib/js/2012/base-v1.js?t=20140126" charset="gb2312"></script>
    <script type="text/javascript" src="//storage.360buyimg.com/jipiao/static/base-v1.js?t=20140126" charset="gb2312"></script>
    <script type="text/javascript" src="//misc.360buyimg.com/jdf/1.0.0/unit/libPath/1.0.0/libPath.js" charset="gb2312"></script>
        <link type="text/css" rel="stylesheet"  href="//misc.360buyimg.com/jdf/1.0.0/unit/??ui-base/5.0.0/ui-base.css,shortcut/5.0.0/shortcut.css,myjd/5.0.0/myjd.css,global-footer/5.0.0/global-footer.css,service/5.0.0/service.css"/>
	<link rel="stylesheet" href="//misc.360buyimg.com/virtuals/lvyou/2015/css/nav.css">
    <link rel="stylesheet" type="text/css" href="//jipiao.jd.com/scripts/newsuggest/css/suggest.css?t=20120306" />
    <link rel="stylesheet" type="text/css" href="//misc.360buyimg.com/virtuals/jipiao/skin/ticket.wineshop.css?t=20120306"  />
    <link type="text/css" rel="stylesheet" href="//misc.360buyimg.com/virtuals/jipiao/skin/base.css?t=20120306"/>
    <link type="text/css" rel="stylesheet" href="//misc.360buyimg.com/virtuals/jipiao/skin/ticket.tanchu.css?t=20120306"/>
    <style type="text/css">
        .breadcrumb{
            display: none;
        }
        #o-air{
            width: 988px !important;
            margin-top: 10px;
        }
        #o-airport{
            padding:10px 0;
        }
        #o-airport li{
            width: 14.2%;
        }
    </style>
    <script type="text/javascript" src="//misc.360buyimg.com/virtuals/lib/js/virtulas.js?t=20121025"></script>
    <script type="text/javascript" src="//jipiao.jd.com/scripts/datepicker2/datepicker.js?t=20121220"></script>
    <script src="//jipiao.jd.com/scripts/datepicker2/airplane-datepicker.js?t=20120306"></script>
    <script type="text/javascript" src="//jipiao.jd.com/scripts/query/homePage.js?t=20121225"></script>
    <script type="text/javascript" src="//jipiao.jd.com/scripts/query/homePageforgj.js?t=20131119" ></script>

	<script type="text/javascript" src="//jipiao.jd.com/scripts/newsuggest/j.suggest.js?t=20120306"></script>
<script type="text/javascript">



</script>
<script id='instances' type='text/javascript'>
    var geminiCssContent = "._Domjipiao122202_Domjipiao122202{display:block !important;} ";
    var geminiStyle = document.createElement('style');
    geminiStyle.setAttribute("name","gemini_prepare_css");
    geminiStyle.setAttribute("type",'text/css');
    if (geminiStyle.styleSheet) {
        geminiStyle.styleSheet.cssText = geminiCssContent;
    } else {
        geminiStyle.appendChild(document.createTextNode(geminiCssContent));
    }
    document.getElementsByTagName("head")[0].appendChild(geminiStyle);
    if( typeof geminiMap == "undefined" ){
        geminiMap = function GeminiMap(){
            var instanceEntry = instanceEntry || {};
            return{
                add:function(key,value){
                    instanceEntry[key]=value;
                    if( typeof geminiNew != "undefined" ){
                        geminiNew.api.reCheckInstance(key,value);
                    }
                },
                getAll:function(){
                    return instanceEntry;
                }
            }
        }();
    }
    geminiMap.add('Domjipiao122202',{id:'Domjipiao122202',divide:'normal'  ,divideCallback:'css',dot:'testZone'  });
</script>
<script  type='text/javascript'>
    if( document.getElementById("gemini_divide_script") == null ){
        var geminiControllerScript = document.createElement("script");
        geminiControllerScript.setAttribute("id","gemini_divide_script")
        geminiControllerScript.setAttribute("src","//static.360buyimg.com/gemini/gemini/gemini.mini.js");
        geminiControllerScript.setAttribute("type", "text/javascript");
        document.getElementsByTagName("head")[0].appendChild(geminiControllerScript);
    }
</script>

</head>


<body id="jipiao">
    <link rel="stylesheet" href="//misc.360buyimg.com/virtuals/jipiao/1.0.0/css/count.css">
<script type="text/javascript" >
    seajs.use(['//misc.360buyimg.com/virtuals/jipiao/1.0.0/js/giftVoucher.js'], function() {
        $("#rightsideCoupon").coupon({
            theme:"优惠礼包"
        });
    });
</script>
<div id="rightsideCoupon">
</div>
    <script type="text/javascript">
        seajs.use(['jdf/1.0.0/unit/shortcut/5.0.0/shortcut.js'],function(shortcut){
            shortcut();
        });
    </script>
    <!--[if !ie]>顶部内容<![endif]-->
    
    <!--[if !ie]>顶部内容<![endif]-->
    <link rel="stylesheet" href="//misc.360buyimg.com/virtuals/jipiao/20140307/skin/jipiao.css?t=20141010">
<!--shortcut start-->
<div id="shortcut-2014">
	<div class="w">
    	<ul class="fl">
    		<li id="ttbar-home"><i class="iconfont">&#xe608;</i><a href="//www.jd.com/" target="_blank">京东首页</a></li>
    	</ul>
    	<ul class="fr">
			<li class="fore1" id="ttbar-login">
				<a href="javascript:login();" class="link-login">你好，请登录</a>&nbsp;&nbsp;<a href="javascript:regist();" class="link-regist style-red">免费注册</a>
			</li>
			<li class="spacer"></li>
			<li class="fore2">
				<div class="dt">
					<a target="_blank" href="//order.jd.com/center/list.action">我的订单</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore3 dorpdown" id="ttbar-myjd">
				<div class="dt cw-icon">
					<!-- <i class="ci-right"><s>◇</s></i> -->
					<a target="_blank" href="//home.jd.com/">我的京东</a><i class="iconfont">&#xe605;</i>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore4">
				<div class="dt">
					<a target="_blank" href="//vip.jd.com/">京东会员</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore5">
				<div class="dt">
					<a target="_blank" href="//b.jd.com/">企业采购</a>
				</div>
			</li>
			<li class="spacer"></li>
			<li class="fore6 dorpdown" id="ttbar-serv">
				<div class="dt cw-icon">
					<!-- <i class="ci-right"><s>◇</s></i> -->
					客户服务<i class="iconfont">&#xe605;</i>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore7 dorpdown" id="ttbar-navs">
				<div class="dt cw-icon">
					<!-- <i class="ci-right"><s>◇</s></i> -->
					网站导航<i class="iconfont">&#xe605;</i>
				</div>
				<div class="dd dorpdown-layer"></div>
			</li>
			<li class="spacer"></li>
			<li class="fore8 dorpdown" id="ttbar-apps">
				<div class="dt cw-icon">
					<!-- <i class="ci-left"></i> -->
					<!-- <i class="ci-right"><s>◇</s></i> -->
					<a target="_blank" href="//app.jd.com/">手机京东</a>
				</div>
			</li>
    	</ul>
		<span class="clr"></span>
    </div>
</div>
<div id="o-header-2013"><div id="header-2013" style="display:none;"></div></div>
<!--shortcut end-->
<!--[if !ie]>顶部内容<![endif]-->
<div id="top-nav-bd">
    <div class="top-nav top-nav-new">
        <div class="w cfix">
            <h1 class="logo">
                <a href="//trip.jd.com/" title="京东旅行"><img src="//misc.360buyimg.com/virtuals/lvyou/2015/css/i/triplogo.png" alt="旅游特价机票、火车票、酒店预订" />旅游特价机票、火车票、酒店预订- 京东</a>
                旅游特价机票、火车票、酒店预订- 京东
            </h1>
            <ul class="nav-list" id="j_trip_nav">
                <li data-http = "trip" clstag="pageclick|keycount|trip_2015032417|1"><a class="a-nav" href="//trip.jd.com/">首页</a></li>
                <li data-http = "jipiao" ><a class="a-nav" href="//jipiao.jd.com/" clstag="pageclick|keycount|trip_2015032418|1">机票<i class="nav-icon xianshihui"></i></a>
                    <div class="nav-show" id="kjp"><div class="cfix uls uls-jp"><span clstag="pageclick|keycount|trip_2015032418|1"><a href="//jipiao.jd.com/">国内机票<i class="nav-icon hot"></i></a></span><span clstag="pageclick|keycount|trip_2015032419|1"><a href="//ijipiao.jd.com/">国际/港澳台机票</a></span></div></div>
                </li>
                <li data-http = "hotel"><a class="a-nav" clstag="pageclick|keycount|trip_2015032420|1" href="//hotel.jd.com/">酒店</a>
                    <div class="nav-show" id="kjd"><div class="cfix uls uls-jd"><span clstag="pageclick|keycount|trip_2015032420|1"><a href="//hotel.jd.com/">国内 · 港澳台</a></span><span clstag="pageclick|keycount|trip_2015032421|1"><a href="//ihotel.jd.com" id="j_trip_hotel">海外酒店<i class="nav-icon hot"></i></a></span></div></div>
                </li>
                <li data-http = "visa" clstag="pageclick|keycount|trip_2015032422|1"><a class="a-nav" href="//visa.jd.com/">签证</a></li>
                <li data-http = "dujia"><a class="a-nav" clstag="pageclick|keycount|trip_2015032423|1" href="//dujia.jd.com/">度假</a>
                    <div class="nav-show" id="kdj"><div class="cfix uls uls-dj"><span clstag="pageclick|keycount|trip_2015032418|1"><a href="//dujia.jd.com/tours">跟团游</a></span><span clstag="pageclick|keycount|trip_2015032419|1"><a href="//dujia.jd.com/pkg">自助游<i class="nav-icon new" style="left:40px;"></i></a></span></div></div>
                </li>
                <li data-http = "menpiao" clstag="pageclick|keycount|trip_2015032425|1"><a class="a-nav" href="//menpiao.jd.com/">门票<i class="nav-icon new"></i></a></li>
                <li data-http = "train" clstag="pageclick|keycount|trip_2015032426|1"><a class="a-nav" href="//train.jd.com/">火车票</a></li>
                <li data-http = "youlun" clstag="pageclick|keycount|trip_2015032427|1"><a class="a-nav" href="//youlun.jd.com/">邮轮</a></li>
                <li data-http = "ct" ><a class="a-nav" href="//mice.jd.com/" clstag="pageclick|keycount|trip_2015032428|1">商旅</a>
                    <div class="nav-show" id="kct"><div class="cfix uls uls-ct"><span clstag="pageclick|keycount|201507301|1"><a href="//ct.jd.com/">差旅管理</a></span><span clstag="pageclick|keycount|201511261|3"><a href="//mice.jd.com/">会奖MICE<i class="nav-icon new"></i></a></span></div></div>
                </li>
                <li data-http = "ddwl" clstag="pageclick|keycount|trip_2015032427|1"><a class="a-nav" href="//ddwl.jd.com/">目的地<i class="nav-icon"></i></a></li>
            </ul>
            <dl class="orders" id="j_trip_order">
                <dt><span class="tx"><img id="j_trip_photo" src="//misc.360buyimg.com/virtuals/lvyou/2015/css/i/no-img.jpg"/><a class="txbg" href="//i.jd.com/user/userinfo/showImg.html" target="_blank"></a></span><strong>我的旅行订单</strong><b></b></dt>
                <dd>
                    <ul>
                        <li class="li-sp">订单信息</li>
                        <li><a href="//order.jd.com/center/list.action?t=35">我的机票订单<i></i></a></li>
                        <li><a href="//order.jd.com/center/list.action?t=39-111">我的酒店订单<i></i><em class="nav-icon hot"></em></a></li>
                        <li><a href="//dujia.jd.com/order/orderList.html">我的度假订单<i></i></a></li>
                        <li><a href="//menpiao.jd.com/order/list">我的景点订单<i></i></a></li>
                        <li><a href="//train.jd.com/order/myOrder.html">我的火车票订单<i></i></a></li>
                        <!-- <li><a href="//meeting.jd.com/order/orderCenter">我的商旅订单<i></i></a></li> -->
                    </ul>
                </dd>
            </dl>
        </div>
    </div>
    <div class="top-nav-bg"></div>
</div>
<script>
    seajs.use(location.protocol + '//misc.360buyimg.com/virtuals/lvyou/2015/js/nav.js', function() {
    })
</script>


<!-- header end -->
<script type="text/javascript">
	jQuery.ajax({
		url:'//jipiao.jd.com/ajaxTicket/queryAdbyKey.action',
		type: 'GET',
		data: { aid : '0_0_7911' },
		dataType:'json',
		success:function(data){
			if(data)
        	$("#headtop").html(data);
		}
	});
	
(function(){if(pageConfig.navId){var object=document.getElementById("nav-"+pageConfig.navId);if(object)object.className+=" curr";}})();
function triporder(){
 var $menu = $("#tripordermenu")
 var $dd = $menu.parent().parent()

 $(".t-order").mouseenter(function(){
     $dd.addClass("hover")
 }).mouseleave(function(){
     $dd.removeClass("hover")
 })
}
triporder();
</script>

 <div class="w">
	<div id="crumb" class="breadcrumb">
        <h1><a href="/">机票</a></h1>
        <span>
            &nbsp;&nbsp;&nbsp;<a href="//hotel.jd.com">酒店</a>
        </span>
        <div class="extra"></div>
    </div>
</div>
<div class="w main">
    <input id="cityListURL" type="hidden" value="/ajaxTicket/queryCityInfo.action"/>
    <input id="isFromJipiaoFlightSearch" type="hidden" value="1"/>
    <input id="isSearch" type="hidden" value="0"/>
    <input id="defaultDate" type="hidden" value="2018-10-21"/>
     <input id="currentDate" type="hidden" value="2018-10-20"/>
    <div class="right" id="o-air">
        <div class="o-mt"><h2><s></s>网上办理乘机</h2></div>
        <div class="m" id="o-explain">
            <div class="mc"><p>旅客可以通过特定的值机凭证在航空公司网站上获全部乘机信息，并根据屏幕提示操作选择座位、确认信息并最终获得登机牌、发票。整个过程完全由旅客自行操作，是一种全新DIY值机方式。</p></div>
        </div>
        <div class="m" id="o-airport">

            <div class="nc">
                <ul>
                    <li><a href="http://www.airchina.com.cn/"><img src="//jipiao.jd.com/htm/img/advimg/air_07.png" width="126" height="126" alt="中国国际航空公司" /></a></li>
                    <li><a href="http://airport.csair.com/cki/app"><img src="//jipiao.jd.com/htm/img/advimg/air_09.png" width="126" height="126" alt="中国南方航空" /></a></li>
                    <li><a href="http://www.shenzhenair.com/?WT.srch=1&WT.mc_id=sem-baidu-brand-logo"><img src="//jipiao.jd.com/htm/img/advimg/air_11.png" width="126" height="126" alt="深圳航空" /></a></li>
                    <li><a href="http://www.hnair.com/"><img src="//jipiao.jd.com/htm/img/advimg/air_13.png" width="126" height="126" alt="海南航空" /></a></li>
                    <li><a href="http://www.ceair.com/server/"><img src="//jipiao.jd.com/htm/img/advimg/air_19.png" width="126" height="126" alt="中国东方航空" /></a></li>
                    <li><a href="http://www.ceair.com/fm.html"><img src="//jipiao.jd.com/htm/img/advimg/air_20.png" width="126" height="126" alt="上海航空公司" /></a></li>
                    <li><a href="http://www.xiamenair.com.cn/"><img src="//jipiao.jd.com/htm/img/advimg/air_21.png" width="126" height="126" alt="厦门航空" /></a></li>

                </ul>
            </div>
        </div>
    </div>

</div>

 <script type="text/javascript" src="/scripts/query/city.js"></script>
 <script type="text/javascript" src="/scripts/datepicker2/datepickergj.js"></script>
 <script type="text/javascript">
     function tabchange(){
         $("#fore1").click(function(){
             $("#fore2").parent().parent().removeClass("curr");
             $(this).parent().parent().addClass("curr");
             $("#search-gj").hide();
             $("#search-gn").show();
         });
         $("#fore2").click(function(){
             $("#fore1").parent().parent().removeClass("curr");
             $(this).parent().parent().addClass("curr");
             $("#search-gn").hide();
             $("#search-gj").show();
             gjinitAutoComplete();
         });
     }
     tabchange();
 </script>

 <div class="recommend gnrecommend"  style="display:none;position: absolute;background:#FFF; left:10px; top:50px;" onmo="this.hide()">
     <div class="mt1">
         <div class="mt_text">热门城市</div>
         <ul class="tab">
             <li class="curr"  data-widget="tab-item"><s></s><b></b><a href="javascript:;">热门城市</a></li>
             <li  data-widget="tab-item"><s></s><b></b><a href="javascript:;">A</a><a href="javascript:;">B</a><a href="javascript:;">C</a><a href="javascript:;">D</a><a href="javascript:;">E</a><a
                     href="javascript:;">F</a><a href="javascript:;">G</a><a href="javascript:;">H</a></li>
             <li  data-widget="tab-item"><s></s><b></b><a href="javascript:;">I</a><a href="javascript:;">J</a><a href="javascript:;">K</a><a href="javascript:;">L</a><a href="javascript:;">M</a><a
                     href="javascript:;">N</a><a href="javascript:;">O</a><a href="javascript:;">P</a></li>
             <li  data-widget="tab-item"><s></s><b></b><a href="javascript:;">Q</a><a href="javascript:;">R</a><a href="javascript:;">S</a><a href="javascript:;">T</a><a href="javascript:;">U</a><a
                     href="javascript:;">V</a><a href="javascript:;">W</a><a href="javascript:;">X</a><a href="javascript:;">Y</a><a href="javascript:;">Z</a></li>
         </ul>
     </div>
     <div id="cityDatas" class="mc1" clickId="">
         <div  data-widget="tab-content" class="form fore tabcon">
             <div class="fl">&nbsp;</div>
             <div class="fn"><a href="javascript:;" data="北京">北京</a><a href="javascript:;" data="上海">上海</a><a href="javascript:;" data="深圳">深圳</a><a
                     href="javascript:;" data="杭州">杭州</a><a href="javascript:;" data="广州">广州</a><a href="javascript:;" data="成都">成都</a><a href="javascript:;"
                                                                                                         data="南京">南京</a><a
                     href="javascript:;" data="武汉">武汉</a><a href="javascript:;" data="长沙">长沙</a><a href="javascript:;" data="昆明">昆明</a><a href="javascript:;"
                                                                                                         data="西安">西安</a><a
                     href="javascript:;" data="青岛">青岛</a><a href="javascript:;" data="厦门">厦门</a><a href="javascript:;" data="天津">天津</a><a href="javascript:;"
                                                                                                         data="大连">大连</a><a
                     href="javascript:;" data="重庆">重庆</a><a href="javascript:;" data="三亚">三亚</a><a href="javascript:;" data="福州">福州</a><a href="javascript:;"
                                                                                                         data="郑州">郑州</a><a
                     href="javascript:;" data="呼和浩特">呼和浩特</a><a href="javascript:;" data="宁波">宁波</a><a href="javascript:;" data="太原">太原</a><a href="javascript:;"
                                                                                                             data="乌鲁木齐">乌鲁木齐</a><a
                     href="javascript:;" data="沈阳">沈阳</a></div>
         </div>
         <div  data-widget="tab-content" class="form hide tabcon"   >
             <div class="fl">A</div>
             <div id="A" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">B</div>
             <div id="B" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">C</div>
             <div id="C" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">D</div>
             <div id="D" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">E</div>
             <div id="E" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">F</div>
             <div id="F" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">G</div>
             <div id="G" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">H</div>
             <div id="H" class="fn"></div>
         </div>
         <div  data-widget="tab-content" class="form hide tabcon"    >
             <!--
               <div class="fl">I</div>
               <div  id="I"  class="fn"></div>
               <div class="clr"></div>
             -->
             <div class="fl">J</div>
             <div id="J" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">K</div>
             <div id="K" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">L</div>
             <div id="L" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">M</div>
             <div id="M" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">N</div>
             <div id="N" class="fn"></div>
             <div class="clr"></div>
             <!--
              <div class="fl">O</div>
              <div  id="O" class="fn"></div>
              <div class="clr"></div>
             -->
             <div class="fl">P</div>
             <div id="P" class="fn"></div>
         </div>
         <div  data-widget="tab-content" class="form hide tabcon" >
             <div class="fl">Q</div>
             <div id="Q" class="fn"></div>
             <div class="clr"></div>
             <!--
               <div class="fl">R</div>
               <div  id="R" class="fn"></div>
               <div class="clr"></div>
             -->
             <div class="fl">S</div>
             <div id="S" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">T</div>
             <div id="T" class="fn"></div>
             <div class="clr"></div>
             <!--
              <div class="fl">U</div>
              <div  id="U" class="fn"></div>
              <div class="clr"></div>

              <div  id="V" class="fl">V</div>
              <div class="fn"></div>
              <div class="clr"></div>
             -->
             <div class="fl">W</div>
             <div id="W" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">X</div>
             <div id="X" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">Y</div>
             <div id="Y" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">Z</div>
             <div id="Z" class="fn"></div>
         </div>
     </div>
 </div>



 <div class="recommend gjrecommend" style="display:none;position: absolute;background:#FFF; left:10px; top:50px;" onmo="this.hide()">
     <div class="mt1">
         <div class="mt_text">热门城市</div>
         <ul class="tab">
             <li class="curr" data-widget="tab-item"><s></s><b></b><a href="javascript:;">热门</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">ABCDEF</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">GHIJ</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">KLMNO</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">PQRSTUVW</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">XYZ</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">国际</a></li>
         </ul>
     </div>
     <div id="gjcityDatas" class="mc1" clickId="">
         <div class="form fore tabcon"  data-widget="tab-content" id="0hot">
         </div>
         <div class="form hide tabcon"  data-widget="tab-content" id="ABCDEF">

             <div class="fl">A</div>
             <div id="gjA" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">B</div>
             <div id="gjB" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">C</div>
             <div id="gjC" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">D</div>
             <div id="gjD" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">E</div>
             <div id="gjE" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">F</div>
             <div id="gjF" class="fn"></div>
             <div class="clr"></div>
         </div>
         <div class="form hide tabcon"  data-widget="tab-content" id="ABCDEF">
             <div class="fl">G</div>
             <div id="gjG" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">H</div>
             <div id="gjH" class="fn"></div>
             <div class="fl">J</div>
             <div id="gjJ" class="fn"></div>
             <div class="clr"></div>
         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="KLMNO">
             <div class="fl">K</div>
             <div id="gjK" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">L</div>
             <div id="gjL" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">M</div>
             <div id="gjM" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">N</div>
             <div id="gjN" class="fn"></div>
             <div class="clr"></div>
         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="PQRSTUVW">
             <div class="fl">Q</div>
             <div id="gjQ" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">S</div>
             <div id="gjS" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">T</div>
             <div id="gjT" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">W</div>
             <div id="gjW" class="fn"></div>
             <div class="clr"></div>
         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="XYZ">
             <div class="fl">X</div>
             <div id="gjX" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">Y</div>
             <div id="gjY" class="fn"></div>
             <div class="clr"></div>
             <div class="fl">Z</div>
             <div id="gjZ" class="fn"></div>
         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="foreign">
         </div>
     </div>
 </div>

 <div class="recommend gjrecommend2" style="display:none;position: absolute;background:#FFF; left:10px; top:50px;" onmo="this.hide()" style="display:none;position: absolute;background:#FFF; left:10px; top:50px;">
     <div class="mt1">
         <div class="mt_text">热门城市</div>
         <ul class="tab">
             <li class="curr" data-widget="tab-item"><s></s><b></b><a href="javascript:;">热门</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">亚洲</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">欧洲</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">美洲</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">非洲</a></li>
             <li data-widget="tab-item"><s></s><b></b><a href="javascript:;">大洋洲</a></li>
         </ul>
     </div>
     <div id="gjcityDatas2" class="mc1" clickId="">
         <div class="form fore tabcon" data-widget="tab-content" id="hot">

         </div>
         <div class="form hide tabcon" data-widget="tab-content"  id="asia">

         </div>
         <div class="form hide tabcon" data-widget="tab-content"  id="europe">

         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="america">

         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="africa">

         </div>
         <div class="form hide tabcon" data-widget="tab-content" id="oceania">

         </div>
     </div>
 </div>

 <div id='suggestDepCity' class="ac_results">
 </div>
 <div id='suggestArrCity' class="ac_results">
 </div>
 <div id='gjsuggestDepCity' class="ac_results">  </div>
 <div id='gjsuggestArrCity' class="ac_results"></div>

 <script>
     document.getElementById("searchForm").onsubmit = function(e){
         var evt = e || event;
         var ecd = evt.which || evt.keyCode;
         return ecd == 13 ?false : true;
     };

     function gjCityChange(){
         var to = $("#gjdepCity").val()
         var from = $("#gjarrCity").val()
         $("#gjdepCity").val(from)
         $("#gjarrCity").val(to)

     }
 </script>


 <div class="w">
     <input id="defaultDate" type="hidden" value="2018-10-21"/>
     <input id="currentDate" type="hidden" value="2018-10-20"/>
     <input id="currentTime" type="hidden" value=""/>
     <input type="hidden" id="gjqueryDepDate" name="gjqueryDepDate" value="2018-10-21"/>
     <input type="hidden" id="gjqueryArrDate" name="gjqueryArrDate" value="2018-10-21"/>
     <input id="cityListURL" type="hidden" value="/ajaxTicket/queryCityInfo.action"/>
     <input id="dingYueEmailURL" type="hidden" value="//jipiao.jd.com/bookEmail.action" />
     <input id="isSearch" type="hidden" value="0"/>
     <input id="isFromJipiaoFlightSearch" type="hidden" value="1"/>

 </div>
 



<span class="clr"></span>

<!--[if !ie]>底部内容开始<![endif]-->

    <!--[if !ie]>底部内容开始<![endif]-->
          <!--service start-->
<div id="service-2017">
	<div class="w">
		<ol class="slogen">
			<li class="item fore1">
				<i>多</i>品类齐全，轻松购物
			</li>
			<li class="item fore2">
				<i>快</i>多仓直发，极速配送
			</li>
			<li class="item fore3">
				<i>好</i>正品行货，精致服务
			</li>
			<li class="item fore4">
				<i>省</i>天天低价，畅选无忧
			</li>
		</ol>
	</div>
	<div class="jd-help">
		<div class="w">
			<div class="wrap">
				<dl class="fore1">
					<dt>购物指南</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-29.html">购物流程</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-151.html">会员介绍</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-297.html">生活旅行/团购</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue.html">常见问题</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-136.html">大家电</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/index.html">联系客服</a></dd>
				</dl>
				<dl class="fore2">		
					<dt>配送方式</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-81-100.html">上门自提</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-81.html">211限时达</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/103-983.html">配送服务查询</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/109-188.html">配送费收取标准</a></dd>				
					<dd><a target="_blank" href="//help.joybuy.com/help/question-list-201.html">海外配送</a></dd>
				</dl>
				<dl class="fore3">
					<dt>支付方式</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-172.html">货到付款</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-173.html">在线支付</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-176.html">分期付款</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-174.html">邮局汇款</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-175.html">公司转账</a></dd>
				</dl>
				<dl class="fore4">		
					<dt>售后服务</dt>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/321-981.html">售后政策</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-132.html">价格保护</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/130-978.html">退款说明</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//myjd.jd.com/repair/repairs.action">返修/退换货</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//help.jd.com/user/issue/list-50.html">取消订单</a></dd>
				</dl>
				<dl class="fore5">
					<dt>特色服务</dt>	
					<dd><a target="_blank" href="//help.jd.com/user/issue/list-133.html">夺宝岛</a></dd>
					<dd><a target="_blank" href="//help.jd.com/user/issue/list-134.html">DIY装机</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//fuwu.jd.com/">延保服务</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//o.jd.com/market/index.action">京东E卡</a></dd>				
					<dd><a rel="nofollow" target="_blank" href="//mobile.jd.com/">京东通信</a></dd>
					<dd><a rel="nofollow" target="_blank" href="//s.jd.com/">京东JD+</a></dd>
				</dl>
				<span class="clr"></span>
			</div>
		</div>
	</div>
</div>
<!--service end-->
        <!--footer start-->
<div id="footer-2017">
	<div class="w">
		<div class="copyright_links">
			<p>
				<a href="//about.jd.com" target="_blank">关于我们</a><span class="copyright_split">|</span>
				<a href="//about.jd.com/contact/" target="_blank">联系我们</a><span class="copyright_split">|</span>
				<a href="//help.jd.com/user/custom.html" target="_blank">联系客服</a><span class="copyright_split">|</span>
				<a href="//vc.jd.com/cooperation.html" target="_blank">合作招商</a><span class="copyright_split">|</span>
				<a href="//helpcenter.jd.com/venderportal/index.html" target="_blank">商家帮助</a><span class="copyright_split">|</span>
				<a href="//jzt.jd.com" target="_blank">营销中心</a><span class="copyright_split">|</span>
				<a href="//app.jd.com/" target="_blank">手机京东</a><span class="copyright_split">|</span>
				<a href="//club.jd.com/links.aspx" target="_blank">友情链接</a><span class="copyright_split">|</span>
				<a href="//media.jd.com/" target="_blank">销售联盟</a><span class="copyright_split">|</span>
				<a href="//club.jd.com/" target="_blank">京东社区</a><span class="copyright_split">|</span>
				<a href="//sale.jd.com/act/FTrWPesiDhXt5M6.html" target="_blank">风险监测</a><span class="copyright_split">|</span>
				<a href="//about.jd.com/privacy/" target="_blank">隐私政策</a><span class="copyright_split">|</span>
				<a href="//gongyi.jd.com" target="_blank">京东公益</a><span class="copyright_split">|</span>
				<a href="//en.jd.com/" target="_blank">English Site</a><span class="copyright_split">|</span>
				<a href="//corporate.jd.com/" target="_blank">Media & IR</a>
			</p>
		</div>
		<div class="copyright_info">
			<p>
				<a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11000002000088" target="_blank">京公网安备 11000002000088号</a><span class="copyright_split">|</span><span>京ICP证070359号</span><span class="copyright_split">|</span>
				<a href="//img14.360buyimg.com/da/jfs/t256/349/769670066/270505/3b03e0bb/53f16c24N7c04d9e9.jpg" target="_blank">互联网药品信息服务资格证编号(京)-经营性-2014-0008</a><span class="copyright_split">|</span><span>新出发京零 字第大120007号</span></p>
			<p><span>互联网出版许可证编号新出网证(京)字150号</span><span class="copyright_split">|</span>
				<a href="//sale.jd.com/act/pQua7zovWdJfcIn.html" target="_blank">出版物经营许可证</a><span class="copyright_split">|</span>
				<a href="//misc.360buyimg.com/wz/wlwhjyxkz.jpg" target="_blank">网络文化经营许可证京网文[2014]2148-348号</a><span class="copyright_split">|</span><span>违法和不良信息举报电话：4006561155</span></p>
			<p><span class="copyright_text">Copyright &copy; 2004 - <em id="copyright_year">2018</em>  京东JD.com 版权所有</span><span class="copyright_split">|</span><span>消费者维权热线：4006067733</span>
				<a href="//sale.jd.com/act/7Y0Rp81MwQqc.html" target="_blank" class="copyright_license">经营证照</a>
				<span class="copyright_split">|</span>
				<span>(京)网械平台备字(2018)第00003号</span>
				<span class="copyright_split">|</span>
				<a href="//storage.jd.com/imgtools/cbdaa22553-dccaf290-d1af-11e8-a840-89f99f5f0056.jpeg" target="_blank" class="mod_business_license">营业执照</a>
			</p>
			<p class="mod_copyright_inter">
				<a class="mod_copyright_inter_lk" href="//www.joybuy.com/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0501"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_global"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.jd.ru/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0502"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_rissia"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.jd.id/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0503"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_indonesia"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.joybuy.es/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0504"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_spain"></i><span class="languagefont"></span></a>
				<span class="copyright_split">|</span>
				<a class="mod_copyright_inter_lk" href="//www.jd.co.th/?source=1&visitor_from=3" target="_blank" clstag="h|keycount|btm|btmnavi_null0505"><i class="mod_copyright_inter_ico mod_copyright_inter_ico_thailand"></i><span class="languagefont"></span></a>
			</p>
			<p><span>京东旗下网站：</span>
				<a href="https://www.jdpay.com/" target="_blank">京东钱包</a><span class="copyright_split">|</span>
				<a href="http://www.jcloud.com" target="_blank">京东云</a>
			</p>
		</div>
		<p class="copyright_auth">
			<script type="text/JavaScript">function CNNIC_change(eleId){var str= document.getElementById(eleId).href;var str1 =str.substring(0,(str.length-6));str1+=CNNIC_RndNum(6);
				document.getElementById(eleId).href=str1;}function CNNIC_RndNum(k){var rnd=""; for (var i=0;i
				< k;i++) rnd+=Math.floor(Math.random()*10); return rnd;};(function(){var d=new Date;document.getElementById(
				 "copyright_year").innerHTML=d.getFullYear()})();</script>
					<a id="urlknet" class="copyright_auth_ico copyright_auth_ico_2" onclick="CNNIC_change('urlknet')" oncontextmenu="return false;"
					 name="CNNIC_seal" href="https://ss.knet.cn/verifyseal.dll?sn=2008070300100000031&ct=df&pa=294005" target="_blank">可信网站信用评估</a>
					<a class="copyright_auth_ico copyright_auth_ico_3" href="http://www.cyberpolice.cn/" target="_blank">网络警察提醒你</a>
					<a class="copyright_auth_ico copyright_auth_ico_4" href="https://search.szfw.org/cert/l/CX20120111001803001836" target="_blank">诚信网站</a>
					<a class="copyright_auth_ico copyright_auth_ico_5" href="http://www.12377.cn" target="_blank">中国互联网举报中心</a>
					<a class="copyright_auth_ico copyright_auth_ico_6" href="http://www.12377.cn/node_548446.htm" target="_blank">网络举报APP下载</a>
		</p>
	</div>
</div>
<!--footer end-->
<script type="text/javascript">(function(){var ja = document.createElement('script'); ja.type='text/javascript'; ja.async=true; ja.src='//misc.360buyimg.com/201007/js/ja.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ja,s); })();</script>


    <script type="text/javascript">



</script>
<script type="text/javascript">(function(){ var e=document.createElement('script');e.type='text/javascript';e.async=true; e.src=('https:'==document.location.protocol?'https://cscssl':'http://csc')+'.jd.com/wl.js'; var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s); })(); </script>
</body>
</html>