<!DOCTYPE html><html><head><meta content=webkit name=renderer><meta http-equiv=X-UA-Compatible content="IE=Edge,chrome=1"><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>在线客服</title><script>// if (navigator.appName == "Microsoft Internet Explorer" && parseInt(navigator.appVersion.split(";")[1].replace(
    //     /[ ]/g, "").replace("MSIE", "")) <= 9) {
    //   location.href = 'https://dd1-web.jd.com/jdchat/custom.action' + location.search
    // }</script><link href=//h5static.m.jd.com/act/jmfe-dongdong/css/app.20181012-qaq.css rel=stylesheet></head><body><div id=app></div><script type=text/javascript src=//h5static.m.jd.com/act/jmfe-dongdong/js/manifest.20181012-qaq.js></script><script type=text/javascript src=//h5static.m.jd.com/act/jmfe-dongdong/js/vendor.20181012-qaq.js></script><script type=text/javascript src=//h5static.m.jd.com/act/jmfe-dongdong/js/app.20181012-qaq.js></script></body><script src=//misc.360buyimg.com/??jdf/1.0.0/unit/base/5.0.0/base.js,jdf/lib/jquery-1.6.4.js></script><script src=//wl.jd.com/wl.js></script></html>